import { LocalizedText } from '../i18n.js';

export interface IChingHexagram {
  number: number;
  name: string;
  chinese: string;
  displayName: LocalizedText;
  upperTrigram: string;
  lowerTrigram: string;
  binary: string;
  judgment: LocalizedText;
  image: LocalizedText;
  advice: LocalizedText;
  love: LocalizedText;
  career: LocalizedText;
  health: LocalizedText;
  finance: LocalizedText;
}

export const I_CHING_HEXAGRAMS: IChingHexagram[] = [
  {
    number: 1, name: "qian", chinese: "乾", binary: "111111", upperTrigram: "heaven", lowerTrigram: "heaven",
    displayName: { pt: "O Criativo", en: "The Creative", es: "El Creativo", hi: "सृजनात्मक" },
    judgment: { pt: "Sucesso sublime. Perseverança favorece.", en: "Sublime success. Perseverance furthers.", es: "Éxito sublime. La perseverancia favorece.", hi: "उदात्त सफलता। दृढ़ता लाभ देती है।" },
    image: { pt: "O movimento do céu é poderoso.", en: "The movement of heaven is powerful.", es: "El movimiento del cielo es poderoso.", hi: "आकाश की गति शक्तिशाली है।" },
    advice: { pt: "Ação criativa e liderança.", en: "Creative action and leadership.", es: "Acción creativa y liderazgo.", hi: "सृजनात्मक क्रिया और नेतृत्व।" },
    love: { pt: "Iniciativa e sinceridade.", en: "Initiative and sincerity.", es: "Iniciativa y sinceridad.", hi: "पहल और सच्चाई।" },
    career: { pt: "Liderança natural.", en: "Natural leadership.", es: "Liderazgo natural.", hi: "प्राकृतिक नेतृत्व।" },
    health: { pt: "Energia vital forte.", en: "Strong vital energy.", es: "Energía vital fuerte.", hi: "मजबूत प्राण ऊर्जा।" },
    finance: { pt: "Oportunidades de crescimento.", en: "Growth opportunities.", es: "Oportunidades de crecimiento.", hi: "विकास के अवसर।" },
  },
  {
    number: 2, name: "kun", chinese: "坤", binary: "000000", upperTrigram: "earth", lowerTrigram: "earth",
    displayName: { pt: "O Receptivo", en: "The Receptive", es: "El Receptivo", hi: "ग्राहक" },
    judgment: { pt: "Sucesso sublime. Receptividade traz fortuna.", en: "Sublime success. Receptivity brings fortune.", es: "Éxito sublime. La receptividad trae fortuna.", hi: "उदात्त सफलता। ग्रहणशीलता भाग्य लाती है।" },
    image: { pt: "A condição da terra é receptiva.", en: "The earth's condition is receptive.", es: "La condición de la tierra es receptiva.", hi: "पृथ्वी की स्थिति ग्रहणशील है।" },
    advice: { pt: "Apoie em vez de liderar.", en: "Support rather than lead.", es: "Apoya en lugar de liderar.", hi: "नेतृत्व के बजाय समर्थन करें।" },
    love: { pt: "Paciência e dedicação.", en: "Patience and dedication.", es: "Paciencia y dedicación.", hi: "धैर्य और समर्पण।" },
    career: { pt: "Trabalho em equipe.", en: "Team work and support.", es: "Trabajo en equipo.", hi: "टीम वर्क और समर्थन।" },
    health: { pt: "Descanso e nutrição.", en: "Rest and nutrition.", es: "Descanso y nutrición.", hi: "विश्राम और पोषण।" },
    finance: { pt: "Investimentos conservadores.", en: "Conservative investments.", es: "Inversiones conservadoras.", hi: "रूढ़िवादी निवेश।" },
  },
  {
    number: 3, name: "zhun", chinese: "屯", binary: "010001", upperTrigram: "water", lowerTrigram: "thunder",
    displayName: { pt: "Dificuldade Inicial", en: "Difficulty at the Beginning", es: "Dificultad al Inicio", hi: "प्रारंभिक कठिनाई" },
    judgment: { pt: "Sucesso sublime. Perseverança favorece.", en: "Sublime success. Perseverance brings fortune.", es: "Éxito sublime. La perseverancia trae fortuna.", hi: "उदात्त सफलता। दृढ़ता भाग्य लाती है।" },
    image: { pt: "Nuvens e trovão: Dificuldade inicial.", en: "Clouds and thunder: Difficulty at the beginning.", es: "Nubes y trueno: Dificultad al inicio.", hi: "बादल और गड़गड़ाहट: प्रारंभिक कठिनाई।" },
    advice: { pt: "Persista com paciência.", en: "Persist with patience.", es: "Persiste con paciencia.", hi: "धैर्य के साथ डटे रहें।" },
    love: { pt: "Paciência é necessária no início.", en: "Patience is needed at the start.", es: "Paciencia es necesaria al inicio.", hi: "शुरुआत में धैर्य की जरूरत होती है।" },
    career: { pt: "Supere obstáculos iniciais.", en: "Overcome initial obstacles.", es: "Supera obstáculos iniciales.", hi: "प्रारंभिक बाधाओं को दूर करें।" },
    health: { pt: "Cuidado durante estresse.", en: "Care during stress.", es: "Cuidado durante el estrés.", hi: "तनाव के दौरान देखभाल।" },
    finance: { pt: "Evite riscos prematuros.", en: "Avoid premature risks.", es: "Evita riesgos prematuros.", hi: "समय से पहले जोखिम से बचें।" },
  },
  {
    number: 4, name: "meng", chinese: "蒙", binary: "100010", upperTrigram: "mountain", lowerTrigram: "water",
    displayName: { pt: "Insensatez Juvenil", en: "Youthful Folly", es: "Insensatez Juvenil", hi: "कम उम्र की मूर्खता" },
    judgment: { pt: "O mestre não procura o jovem tolo.", en: "The teacher does not seek the youthful fool.", es: "El maestro no busca al joven insensato.", hi: "शिक्षक युवा मूर्ख के पीछे नहीं भागता।" },
    image: { pt: "Uma fonte sob a montanha.", en: "A spring under the mountain.", es: "Una fuente bajo la montaña.", hi: "पहाड़ के नीचे एक झरना।" },
    advice: { pt: "Aprenda com humildade.", en: "Learn with humility.", es: "Aprende con humildad.", hi: "विनम्रता के साथ सीखें।" },
    love: { pt: "Busque compreensão mútua.", en: "Seek mutual understanding.", es: "Busca comprensión mutua.", hi: "परस्पर समझ की तलाश करें।" },
    career: { pt: "Peça conselho a mentores.", en: "Seek advice from mentors.", es: "Pide consejo a mentores.", hi: "गुरुओं से सलाह लें।" },
    health: { pt: "Cuide da mente e clareza.", en: "Care for mind and clarity.", es: "Cuida la mente y claridad.", hi: "मन और स्पष्टता का ख्याल रखें।" },
    finance: { pt: "Cuidado com investimentos incertos.", en: "Careful with uncertain investments.", es: "Cuidado con inversiones inciertas.", hi: "अनिश्चित निवेश के साथ सावधान रहें।" },
  },
  {
    number: 5, name: "xu", chinese: "需", binary: "111010", upperTrigram: "water", lowerTrigram: "heaven",
    displayName: { pt: "A Espera", en: "Waiting", es: "La Espera", hi: "प्रतीक्षा" },
    judgment: { pt: "Veracidade brilha. Perseverança traz fortuna.", en: "Veracity shines. Perseverance brings fortune.", es: "La veracidad brilla. La perseverancia trae fortuna.", hi: "सच्चाई चमकती है। दृढ़ता भाग्य लाती है।" },
    image: { pt: "Nuvens no céu sugerem chuva.", en: "Clouds in the sky suggest rain.", es: "Nubes en el cielo sugieren lluvia.", hi: "आकाश में बादल बारिश का संकेत देते हैं।" },
    advice: { pt: "Aguarde o momento certo.", en: "Wait for the right moment.", es: "Espera el momento correcto.", hi: "सही समय का इंतज़ार करें।" },
    love: { pt: "Deixe o tempo amadurecer.", en: "Let time mature relationships.", es: "Deja que el tiempo madure la relación.", hi: "समय को रिश्तों को परिपक्व होने दें।" },
    career: { pt: "Não force eventos profissionais.", en: "Do not force professional events.", es: "No fuerces eventos profesionales.", hi: "पेशेवर घटनाओं पर दबाव न डालें।" },
    health: { pt: "Paciência e autocuidado.", en: "Patience and self-care.", es: "Paciencia y autocuidado.", hi: "धैर्य और आत्म-देखभाल।" },
    finance: { pt: "Aguarde oportunidades sólidas.", en: "Wait for solid opportunities.", es: "Espera oportunidades sólidas.", hi: "ठोस अवसरों का इंतज़ार करें।" },
  },
  {
    number: 6, name: "song", chinese: "訟", binary: "101110", upperTrigram: "heaven", lowerTrigram: "water",
    displayName: { pt: "O Conflito", en: "Conflict", es: "El Conflicto", hi: "संघर्ष" },
    judgment: { pt: "Sinceridade obstruída. Parar no meio traz fortuna.", en: "Sincerity is obstructed. Stopping halfway brings fortune.", es: "Sinceridad obstruida. Detenerse a mitad trae fortuna.", hi: "ईमानदारी बाधित है। आधे रास्ते में रुकना भाग्य लाता है।" },
    image: { pt: "Céu e água se movem em direções opostas.", en: "Heaven and water move in opposite directions.", es: "El cielo y el agua se mueven en direcciones opuestas.", hi: "आकाश और जल विपरीत दिशाओं में चलते हैं।" },
    advice: { pt: "Evite disputas prolongadas.", en: "Avoid prolonged disputes.", es: "Evita disputas prolongadas.", hi: "लंबे विवादों से बचें।" },
    love: { pt: "Busque reconciliação e clareza.", en: "Seek reconciliation and clarity.", es: "Busca reconciliación y claridad.", hi: "सुलह और स्पष्टता की तलाश करें।" },
    career: { pt: "Mediação é melhor que litígio.", en: "Mediation is better than litigation.", es: "La mediación es mejor que el litigio.", hi: "मुकदमेबाजी से मध्यस्थता बेहतर है।" },
    health: { pt: "Reduza estresse e tensões.", en: "Reduce stress and tensions.", es: "Reduce el estrés y las tensiones.", hi: "तनाव और तनाव कम करें।" },
    finance: { pt: "Resolva pendências e evite riscos.", en: "Resolve pending issues and avoid risks.", es: "Resuelve asuntos pendientes y evita riesgos.", hi: "लंबित मुद्दों को हल करें और जोखिमों से बचें।" },
  },
  {
    number: 7, name: "shi", chinese: "師", binary: "000010", upperTrigram: "earth", lowerTrigram: "water",
    displayName: { pt: "O Exército", en: "The Army", es: "El Ejército", hi: "सेना" },
    judgment: { pt: "Perseverança e liderança trazem sucesso.", en: "Perseverance and leadership bring success.", es: "La perseverancia y el liderazgo traen éxito.", hi: "दृढ़ता और नेतृत्व सफलता लाते हैं।" },
    image: { pt: "Água no centro da terra.", en: "Water in the center of the earth.", es: "Agua en el centro de la tierra.", hi: "पृथ्वी के केंद्र में जल।" },
    advice: { pt: "Organização e disciplina.", en: "Organization and discipline.", es: "Organización y disciplina.", hi: "संगठन और अनुशासन।" },
    love: { pt: "União em torno de causas comuns.", en: "Unity around common causes.", es: "Unión en torno a causas comunes.", hi: "सामान्य कारणों के इर्द-गिर्द एकता।" },
    career: { pt: "Liderança firme e estratégica.", en: "Firm and strategic leadership.", es: "Liderazgo firme y estratégico.", hi: "दृढ़ और रणनीतिक नेतृत्व।" },
    health: { pt: "Fortaleça seu sistema imunológico.", en: "Strengthen your immune system.", es: "Fortalece tu sistema inmunológico.", hi: "अपनी प्रतिरक्षा प्रणाली को मजबूत करें।" },
    finance: { pt: "Gestão rigorosa de recursos.", en: "Rigorous resource management.", es: "Gestión rigurosa de recursos.", hi: "संसाधनों का कठोर प्रबंधन।" },
  },
  {
    number: 8, name: "bi", chinese: "比", binary: "010000", upperTrigram: "water", lowerTrigram: "earth",
    displayName: { pt: "A União", en: "Union", es: "La Unión", hi: "संघ" },
    judgment: { pt: "Fortuna para quem se une com sinceridade.", en: "Fortune for those who unite with sincerity.", es: "Fortuna para quienes se unen con sinceridad.", hi: "सच्चाई के साथ जुड़ने वालों के लिए भाग्य।" },
    image: { pt: "Água sobre a terra indica união.", en: "Water over the earth indicates union.", es: "El agua sobre la tierra indica unión.", hi: "पृथ्वी पर जल मिलन का संकेत देता है।" },
    advice: { pt: "Colabore e busque aliados.", en: "Collaborate and seek allies.", es: "Colabora y busca aliados.", hi: "सहयोग करें और सहयोगियों की तलाश करें।" },
    love: { pt: "Sintonia e parceria profunda.", en: "Harmony and deep partnership.", es: "Sintonía y compañerismo profundo.", hi: "सद्भाव और गहरी साझेदारी।" },
    career: { pt: "Trabalho colaborativo e networking.", en: "Collaborative work and networking.", es: "Trabajo colaborativo y networking.", hi: "सहयोगात्मक कार्य और नेटवर्किंग।" },
    health: { pt: "Equilíbrio de fluidos corporais.", en: "Balance of bodily fluids.", es: "Equilibrio de fluidos corporales.", hi: "शारीरिक तरल पदार्थों का संतुलन।" },
    finance: { pt: "Sociedades e investimentos em grupo.", en: "Partnerships and group investments.", es: "Sociedades e inversiones en grupo.", hi: "साझेदारी और समूह निवेश।" },
  },
  {
    number: 9, name: "xiao chu", chinese: "小畜", binary: "111011", upperTrigram: "wind", lowerTrigram: "heaven",
    displayName: { pt: "Pequeno Acúmulo", en: "Small Accumulation", es: "Pequeño Acúmulo", hi: "छोटा संचय" },
    judgment: { pt: "Nuvens densas, mas sem chuva ainda.", en: "Dense clouds, but no rain yet.", es: "Nubes densas, pero sin lluvia aún.", hi: "घने बादल, लेकिन अभी तक बारिश नहीं।" },
    image: { pt: "O vento sopra no céu.", en: "The wind blows in the sky.", es: "El viento sopla en el cielo.", hi: "आकाश में हवा चलती है।" },
    advice: { pt: "Paciência com os pequenos progressos.", en: "Patience with small progress.", es: "Paciencia con los pequeños progresos.", hi: "छोटी प्रगति के साथ धैर्य रखें।" },
    love: { pt: "Pequenos gestos fortalecem o laço.", en: "Small gestures strengthen the bond.", es: "Pequeños gestos fortalecen el lazo.", hi: "छोटे इशारे बंधन को मजबूत करते हैं।" },
    career: { pt: "Prepare as bases para o futuro.", en: "Prepare the foundations for the future.", es: "Prepara las bases para el futuro.", hi: "भविष्य के लिए आधार तैयार करें।" },
    health: { pt: "Cuide da respiração e pulmões.", en: "Care for breath and lungs.", es: "Cuida la respiración y pulmones.", hi: "सांस और फेफड़ों का ख्याल रखें।" },
    finance: { pt: "Economia gradual e constante.", en: "Gradual and constant saving.", es: "Ahorro gradual y constante.", hi: "धीरे-धीरे और निरंतर बचत।" },
  },
  {
    number: 10, name: "lü", chinese: "履", binary: "110111", upperTrigram: "heaven", lowerTrigram: "lake",
    displayName: { pt: "A Conduta", en: "Conduct", es: "La Conducta", hi: "आचरण" },
    judgment: { pt: "Pisar na cauda do tigre sem ser mordido.", en: "Treading on the tiger's tail without being bitten.", es: "Pisar la cola del tigre sin ser mordido.", hi: "बिना काटे बाघ की पूंछ पर पैर रखना।" },
    image: { pt: "O céu sobre o lago.", en: "The sky over the lake.", es: "El cielo sobre el lago.", hi: "झील के ऊपर आकाश।" },
    advice: { pt: "Aja com cautela e polidez.", en: "Act with caution and politeness.", es: "Actúa con cautela y cortesía.", hi: "सावधानी और विनम्रता के साथ कार्य करें।" },
    love: { pt: "Respeito mútuo é essencial.", en: "Mutual respect is essential.", es: "El respeto mutuo es esencial.", hi: "परस्पर सम्मान आवश्यक है।" },
    career: { pt: "Navegue com diplomacia.", en: "Navigate with diplomacy.", es: "Navega con diplomacia.", hi: "कूटनीति के साथ चलें।" },
    health: { pt: "Cuidado com os pés e postura.", en: "Care for feet and posture.", es: "Cuidado con los pies y postura.", hi: "पैरों और मुद्रा का ख्याल रखें।" },
    finance: { pt: "Mantenha a integridade financeira.", en: "Maintain financial integrity.", es: "Mantén la integridad financiera.", hi: "वित्तीय अखंडता बनाए रखें।" },
  },
  {
    number: 11, name: "tai", chinese: "泰", binary: "111000", upperTrigram: "earth", lowerTrigram: "heaven",
    displayName: { pt: "A Paz", en: "Peace", es: "La Paz", hi: "शांति" },
    judgment: { pt: "O pequeno vai, o grande vem. Fortuna.", en: "Small goes, great comes. Fortune.", es: "Lo pequeño se va, lo grande viene. Fortuna.", hi: "छोटा जाता है, बड़ा आता है। भाग्य।" },
    image: { pt: "Céu e terra se unem em harmonia.", en: "Heaven and earth unite in harmony.", es: "El cielo y la tierra se unen en armonía.", hi: "आकाश और पृथ्वी सद्भाव में एकजुट होते हैं।" },
    advice: { pt: "Aproveite a fase de expansão.", en: "Enjoy the phase of expansion.", es: "Aprovecha la fase de expansión.", hi: "विस्तार के चरण का आनंद लें।" },
    love: { pt: "Felicidade e plenitude afetiva.", en: "Happiness and emotional fulfillment.", es: "Felicidad y plenitud afectiva.", hi: "खुशी और भावनात्मक पूर्णता।" },
    career: { pt: "Prosperidade e novos horizontes.", en: "Prosperity and new horizons.", es: "Prosperidad y nuevos horizontes.", hi: "समृद्धि और नए क्षितिज।" },
    health: { pt: "Excelente vitalidade e equilíbrio.", en: "Excellent vitality and balance.", es: "Excelente vitalidad y equilibrio.", hi: "उत्कृष्ट जीवन शक्ति और संतुलन।" },
    finance: { pt: "Ganhos significativos e abundância.", en: "Significant gains and abundance.", es: "Ganancias significativas y abundancia.", hi: "महत्वपूर्ण लाभ और प्रचुरता।" },
  },
  {
    number: 12, name: "pi", chinese: "否", binary: "000111", upperTrigram: "heaven", lowerTrigram: "earth",
    displayName: { pt: "A Estagnação", en: "Stagnation", es: "La Estancación", hi: "ठहराव" },
    judgment: { pt: "O grande vai, o pequeno vem. Desfavorável.", en: "Great goes, small comes. Unfavorable.", es: "Lo grande se va, lo pequeño viene. Desfavorable.", hi: "बड़ा जाता है, छोटा आता है। प्रतिकूल।" },
    image: { pt: "Céu e terra se separam.", en: "Heaven and earth separate.", es: "El cielo y la tierra se separan.", hi: "आकाश और पृथ्वी अलग हो जाते हैं।" },
    advice: { pt: "Recolha-se e evite agir agora.", en: "Withdraw and avoid acting now.", es: "Retírate y evita actuar ahora.", hi: "पीछे हटें और अभी कार्य करने से बचें।" },
    love: { pt: "Dificuldades de comunicação.", en: "Communication difficulties.", es: "Dificultades de comunicación.", hi: "संचार की कठिनाइयाँ।" },
    career: { pt: "Bloqueios temporários. Aguarde.", en: "Temporary blocks. Wait.", es: "Bloqueos temporales. Espera.", hi: "अस्थायी रुकावटें। इंतज़ार करें।" },
    health: { pt: "Baixa energia. Descanse mais.", en: "Low energy. Rest more.", es: "Baja energía. Descansa más.", hi: "कम ऊर्जा। अधिक आराम करें।" },
    finance: { pt: "Estagnação financeira. Economize.", en: "Financial stagnation. Save.", es: "Estancamiento financiero. Ahorra.", hi: "वित्तीय ठहराव। बचत करें।" },
  },
  {
    number: 13, name: "tong ren", chinese: "同人", binary: "101111", upperTrigram: "heaven", lowerTrigram: "fire",
    displayName: { pt: "Comunhão", en: "Fellowship", es: "Compañerismo", hi: "फैलोशिप" },
    judgment: { pt: "Sucesso através da união universal.", en: "Success through universal union.", es: "Éxito a través de la unión universal.", hi: "सार्वभौमिक संघ के माध्यम से सफलता।" },
    image: { pt: "O fogo arde sob o céu.", en: "Fire burns under the sky.", es: "El fuego arde bajo el cielo.", hi: "आकाश के नीचे आग जलती है।" },
    advice: { pt: "Busque ideais comuns com outros.", en: "Seek common ideals with others.", es: "Busca ideales comunes con otros.", hi: "दूसरों के साथ समान आदर्शों की तलाश करें।" },
    love: { pt: "Amor baseado em amizade profunda.", en: "Love based on deep friendship.", es: "Amor basado en amistad profunda.", hi: "गहरी दोस्ती पर आधारित प्यार।" },
    career: { pt: "Sucesso em parcerias e grupos.", en: "Success in partnerships and groups.", es: "Éxito en asociaciones y grupos.", hi: "साझेदारी और समूहों में सफलता।" },
    health: { pt: "Boa circulação e calor vital.", en: "Good circulation and vital heat.", es: "Buena circulación y calor vital.", hi: "अच्छा परिसंचरण और महत्वपूर्ण गर्मी।" },
    finance: { pt: "Ganhos em empreendimentos coletivos.", en: "Gains in collective ventures.", es: "Ganancias en proyectos colectivos.", hi: "सामूहिक उद्यमों में लाभ।" },
  },
  {
    number: 14, name: "da you", chinese: "大有", binary: "111101", upperTrigram: "fire", lowerTrigram: "heaven",
    displayName: { pt: "Grande Possessão", en: "Great Possession", es: "Gran Posesión", hi: "बड़ी संपत्ति" },
    judgment: { pt: "Sucesso supremo. Fortuna do céu.", en: "Supreme success. Heavenly fortune.", es: "Éxito supremo. Fortuna del cielo.", hi: "परम सफलता। स्वर्गीय भाग्य।" },
    image: { pt: "O sol brilha alto no céu.", en: "The sun shines high in the sky.", es: "El sol brilla alto en el cielo.", hi: "सूरज आसमान में ऊंचा चमकता है।" },
    advice: { pt: "Brilhe com generosidade.", en: "Shine with generosity.", es: "Brilla con generosidad.", hi: "उदारता के साथ चमकें।" },
    love: { pt: "Brilho e admiração mútua.", en: "Shine and mutual admiration.", es: "Brillo y admiración mutua.", hi: "चमक और आपसी प्रशंसा।" },
    career: { pt: "Reconhecimento e grande liderança.", en: "Recognition and great leadership.", es: "Reconocimiento y gran liderazgo.", hi: "मान्यता और महान नेतृत्व।" },
    health: { pt: "Muita energia e força física.", en: "High energy and physical strength.", es: "Mucha energía y fuerza física.", hi: "उच्च ऊर्जा और शारीरिक शक्ति।" },
    finance: { pt: "Grande prosperidade financeira.", en: "Great financial prosperity.", es: "Gran prosperidad financiera.", hi: "महान वित्तीय समृद्धि।" },
  },
  {
    number: 15, name: "qian", chinese: "謙", binary: "000100", upperTrigram: "earth", lowerTrigram: "mountain",
    displayName: { pt: "A Modéstia", en: "Modesty", es: "La Modestia", hi: "विनम्रता" },
    judgment: { pt: "O modesto terá sucesso.", en: "The modest will have success.", es: "El modesto tendrá éxito.", hi: "विनम्र व्यक्ति सफल होगा।" },
    image: { pt: "A montanha oculta na terra.", en: "The mountain hidden in the earth.", es: "La montaña oculta en la tierra.", hi: "पृथ्वी में छिपा हुआ पहाड़।" },
    advice: { pt: "Mantenha a simplicidade e humildade.", en: "Maintain simplicity and humility.", es: "Mantén la sencillez y la humildad.", hi: "सादगी और विनम्रता बनाए रखें।" },
    love: { pt: "Devotamento discreto e sincero.", en: "Discreet and sincere devotion.", es: "Devoción discreta y sincera.", hi: "सतर्क और सच्ची भक्ति।" },
    career: { pt: "Trabalho silencioso que rende frutos.", en: "Silent work that yields results.", es: "Trabajo silencioso que rinde frutos.", hi: "चुपचाप किया गया काम जो परिणाम देता है।" },
    health: { pt: "Equilíbrio emocional e digestivo.", en: "Emotional and digestive balance.", es: "Equilibrio emocional y digestivo.", hi: "भावनात्मक और पाचन संतुलन।" },
    finance: { pt: "Gestão prudente traz segurança.", en: "Prudent management brings security.", es: "Gestión prudente trae seguridad.", hi: "विवेकपूर्ण प्रबंधन सुरक्षा लाता है।" },
  },
  {
    number: 16, name: "yu", chinese: "豫", binary: "001000", upperTrigram: "thunder", lowerTrigram: "earth",
    displayName: { pt: "O Entusiasmo", en: "Enthusiasm", es: "El Entusiasmo", hi: "उत्साह" },
    judgment: { pt: "Favorece a ação e o movimento.", en: "Favors action and movement.", es: "Favorece la acción y el movimiento.", hi: "कार्रवाई और गति का पक्ष लेता है।" },
    image: { pt: "O trovão ressoa sobre a terra.", en: "Thunder resonates over the earth.", es: "El trueno resuena sobre la tierra.", hi: "धरती पर गड़गड़ाहट गूँजती है।" },
    advice: { pt: "Aja com alegria e planejamento.", en: "Act with joy and planning.", es: "Actúa con alegría y planificación.", hi: "आनंद और योजना के साथ कार्य करें।" },
    love: { pt: "Celebração e alegria a dois.", en: "Celebration and joy together.", es: "Celebración y alegría juntos.", hi: "उत्सव और एक साथ खुशी।" },
    career: { pt: "Inspire outros com seu vigor.", en: "Inspire others with your vigor.", es: "Inspira a otros con tu vigor.", hi: "अपने जोश से दूसरों को प्रेरित करें।" },
    health: { pt: "Boa vitalidade, canalize energia.", en: "Good vitality, channel energy.", es: "Buena vitalidad, canaliza energía.", hi: "अच्छी जीवन शक्ति, ऊर्जा का संचार करें।" },
    finance: { pt: "Iniciativas bem-sucedidas.", en: "Successful initiatives.", es: "Iniciativas exitosas.", hi: "सफल पहल।" },
  },
  {
    number: 17, name: "sui", chinese: "隨", binary: "011001", upperTrigram: "lake", lowerTrigram: "thunder",
    displayName: { pt: "O Seguir", en: "Following", es: "El Seguimiento", hi: "निम्नलिखित" },
    judgment: { pt: "Fortuna. Siga o que é verdadeiro.", en: "Fortune. Follow what is true.", es: "Fortuna. Sigue lo que es verdadero.", hi: "भाग्य। जो सच है उसका पालन करें।" },
    image: { pt: "O trovão repousa no lago.", en: "Thunder rests in the lake.", es: "El trueno descansa en el lago.", hi: "झील में गड़गड़ाहट विश्राम करती है।" },
    advice: { pt: "Saiba quando se adaptar.", en: "Know when to adapt.", es: "Sabe cuándo adaptarte.", hi: "जानें कि कब अनुकूल होना है।" },
    love: { pt: "Adaptabilidade fortalece a relação.", en: "Adaptability strengthens relations.", es: "La adaptabilidad fortalece la relación.", hi: "अनुकूलन क्षमता रिश्तों को मजबूत करती है।" },
    career: { pt: "Siga as tendências corretas.", en: "Follow the right trends.", es: "Sigue las tendencias correctas.", hi: "सही रुझानों का पालन करें।" },
    health: { pt: "Ritmo de sono e descanso.", en: "Sleep and rest rhythm.", es: "Ritmo de sueño y descanso.", hi: "नींद और विश्राम की लय।" },
    finance: { pt: "Acompanhe o mercado com cautela.", en: "Monitor the market with caution.", es: "Sigue el mercado con cautela.", hi: "सावधानी के साथ बाज़ार की निगरानी करें।" },
  },
  {
    number: 18, name: "gu", chinese: "蠱", binary: "100110", upperTrigram: "mountain", lowerTrigram: "wind",
    displayName: { pt: "O Trabalho", en: "Work on the Decayed", es: "El Trabajo en lo Decaído", hi: "क्षय पर कार्य" },
    judgment: { pt: "É favorável atravessar a grande água.", en: "It is favorable to cross the great water.", es: "Es favorable cruzar la gran agua.", hi: "महान जल को पार करना अनुकूल है।" },
    image: { pt: "O vento sopra na base da montanha.", en: "The wind blows at the base of the mountain.", es: "El viento sopla en la base de la montaña.", hi: "पहाड़ के आधार पर हवा चलती है।" },
    advice: { pt: "Corrija erros do passado agora.", en: "Correct past mistakes now.", es: "Corrige errores del pasado ahora.", hi: "अतीत की गलतियों को अभी सुधारें।" },
    love: { pt: "Cure velhas feridas afetivas.", en: "Heal old emotional wounds.", es: "Sana viejas heridas afectivas.", hi: "पुराने भावनात्मक घावों को भरें।" },
    career: { pt: "Reformas e melhorias necessárias.", en: "Necessary reforms and improvements.", es: "Reformas y mejoras necesarias.", hi: "आवश्यक सुधार और उन्नति।" },
    health: { pt: "Desintoxicação e limpeza.", en: "Detoxification and cleansing.", es: "Desintoxicación y limpieza.", hi: "विषहरण और सफाई।" },
    finance: { pt: "Reorganize suas finanças.", en: "Reorganize your finances.", es: "Reorganiza tus finanzas.", hi: "अपने वित्त को पुनर्गठित करें।" },
  },
  {
    number: 19, name: "lin", chinese: "臨", binary: "110000", upperTrigram: "earth", lowerTrigram: "lake",
    displayName: { pt: "A Aproximação", en: "Approach", es: "La Aproximación", hi: "दृष्टिकोण" },
    judgment: { pt: "Sucesso sublime. Fortuna.", en: "Sublime success. Fortune.", es: "Éxito sublime. Fortuna.", hi: "उदात्त सफलता। भाग्य।" },
    image: { pt: "A terra sobre o lago.", en: "The earth over the lake.", es: "La tierra sobre el lago.", hi: "झील के ऊपर की धरती।" },
    advice: { pt: "Aproxime-se com autoridade gentil.", en: "Approach with gentle authority.", es: "Acércate con autoridad gentil.", hi: "सौम्य अधिकार के साथ दृष्टिकोण।" },
    love: { pt: "Novas conexões se aproximam.", en: "New connections approach.", es: "Nuevas conexiones se aproximan.", hi: "नए संबंध करीब आते हैं।" },
    career: { pt: "Oportunidades de crescimento.", en: "Opportunities for growth.", es: "Oportunidades de crecimiento.", hi: "विकास के अवसर।" },
    health: { pt: "Boa energia de primavera.", en: "Good spring energy.", es: "Buena energía de primavera.", hi: "अच्छी वसंत ऊर्जा।" },
    finance: { pt: "Prosperidade em crescimento.", en: "Growing prosperity.", es: "Prosperidad en crecimiento.", hi: "बढ़ती समृद्धि।" },
  },
  {
    number: 20, name: "guan", chinese: "觀", binary: "000011", upperTrigram: "wind", lowerTrigram: "earth",
    displayName: { pt: "A Contemplação", en: "Contemplation", es: "La Contemplación", hi: "चिंतन" },
    judgment: { pt: "Olhar sem agir, como quem medita.", en: "Look without acting, like meditating.", es: "Mirar sin actuar, como quien medita.", hi: "बिना कार्य किए देखें, जैसे ध्यान करना।" },
    image: { pt: "O vento sopra sobre a terra.", en: "The wind blows over the earth.", es: "El viento sopla sobre la tierra.", hi: "पृथ्वी पर हवा चलती है।" },
    advice: { pt: "Observe a situação e reflita.", en: "Observe the situation and reflect.", es: "Observa la situación y reflexiona.", hi: "स्थिति का निरीक्षण करें और चिंतन करें।" },
    love: { pt: "Avalie seus sentimentos.", en: "Evaluate your feelings.", es: "Evalúa tus sentimientos.", hi: "अपनी भावनाओं का मूल्यांकन करें।" },
    career: { pt: "Visão estratégica e observação.", en: "Strategic vision and observation.", es: "Visión estratégica y observación.", hi: "रणनीतिक दृष्टि और अवलोकन।" },
    health: { pt: "Clareza mental e meditação.", en: "Mental clarity and meditation.", es: "Claridad mental y meditación.", hi: "मानसिक स्पष्टता और ध्यान।" },
    finance: { pt: "Estudo de mercado cuidadoso.", en: "Careful market study.", es: "Estudio de mercado cuidadoso.", hi: "सावधानीपूर्वक बाज़ार का अध्ययन।" },
  },
  {
    number: 21, name: "shi ke", chinese: "噬嗑", binary: "100101", upperTrigram: "fire", lowerTrigram: "thunder",
    displayName: { pt: "Morder e Atravessar", en: "Biting Through", es: "Morder y Atravesar", hi: "काटना और पार करना" },
    judgment: { pt: "Sucesso. É favorável administrar a justiça.", en: "Success. It is favorable to administer justice.", es: "Éxito. Es favorable administrar justicia.", hi: "सफलता। न्याय करना अनुकूल है।" },
    image: { pt: "Trovão e relâmpago: Morder e atravessar.", en: "Thunder and lightning: Biting through.", es: "Trueno y relámpago: Morder y atravesar.", hi: "गड़गड़ाहट और बिजली: काटना और पार करना।" },
    advice: { pt: "Remova obstáculos com determinação.", en: "Remove obstacles with determination.", es: "Elimina obstáculos con determinación.", hi: "दृढ़ संकल्प के साथ बाधाओं को दूर करें।" },
    love: { pt: "Resolva conflitos de forma direta.", en: "Solve conflicts directly.", es: "Resuelve conflictos de forma directa.", hi: "विवादों को सीधे हल करें।" },
    career: { pt: "Enfrente problemas e tome decisões.", en: "Face problems and make decisions.", es: "Enfrenta problemas y toma decisiones.", hi: "समस्याओं का सामना करें और निर्णय लें।" },
    health: { pt: "Atenção à mandíbula e dentes.", en: "Attention to jaw and teeth.", es: "Atención a la mandíbula y los dientes.", hi: "जबड़े और दांतों पर ध्यान दें।" },
    finance: { pt: "Resolva disputas financeiras agora.", en: "Resolve financial disputes now.", es: "Resuelve disputas financieras ahora.", hi: "अब वित्तीय विवादों को सुलझाएं।" },
  },
  {
    number: 22, name: "bi", chinese: "賁", binary: "101001", upperTrigram: "mountain", lowerTrigram: "fire",
    displayName: { pt: "A Graça", en: "Grace", es: "La Gracia", hi: "कृपा" },
    judgment: { pt: "Sucesso em pequenas coisas.", en: "Success in small things.", es: "Éxito en pequeñas cosas.", hi: "छोटी-छोटी बातों में सफलता।" },
    image: { pt: "Fogo na base da montanha.", en: "Fire at the base of the mountain.", es: "Fuego en la base de la montaña.", hi: "पहाड़ के आधार पर आग।" },
    advice: { pt: "Valorize a estética e a cortesia.", en: "Value aesthetics and courtesy.", es: "Valora la estética y la cortesía.", hi: "सौंदर्यशास्त्र और शिष्टता को महत्व दें।" },
    love: { pt: "Beleza e romantismo em alta.", en: "Beauty and romance are high.", es: "Belleza y romanticismo en alza.", hi: "सौंदर्य और रोमांस उच्च स्तर पर हैं।" },
    career: { pt: "Apresentação e imagem importam.", en: "Presentation and image matter.", es: "La presentación y la imagen importan.", hi: "प्रस्तुति और छवि मायने रखती है।" },
    health: { pt: "Cuidado com a pele e aparência.", en: "Care for skin and appearance.", es: "Cuidado de la piel y apariencia.", hi: "त्वचा और रूप-रंग का ख्याल रखें।" },
    finance: { pt: "Gastos com arte e decoração.", en: "Spending on art and decoration.", es: "Gastos en arte y decoración.", hi: "कला और सजावट पर खर्च।" },
  },
  {
    number: 23, name: "bo", chinese: "剝", binary: "100000", upperTrigram: "mountain", lowerTrigram: "earth",
    displayName: { pt: "A Desintegração", en: "Splitting Apart", es: "La Desintegración", hi: "विभाजन" },
    judgment: { pt: "Não é favorável agir no momento.", en: "It is not favorable to act at the moment.", es: "No es favorable actuar en el momento.", hi: "फिलहाल कार्य करना अनुकूल नहीं है।" },
    image: { pt: "A montanha repousa sobre a terra.", en: "The mountain rests on the earth.", es: "La montaña descansa sobre la tierra.", hi: "पहाड़ पृथ्वी पर टिका है।" },
    advice: { pt: "Aguarde a tempestade passar.", en: "Wait for the storm to pass.", es: "Espera a que pase la tormenta.", hi: "तूफान के गुजरने का इंतज़ार करें।" },
    love: { pt: "Momento de distanciamento e reflexão.", en: "Time for distance and reflection.", es: "Momento de distanciamiento y reflexión.", hi: "दूरी और चिंतन का समय।" },
    career: { pt: "Evite novos projetos agora.", en: "Avoid new projects now.", es: "Evita nuevos proyectos ahora.", hi: "अब नए प्रोजेक्ट्स से बचें।" },
    health: { pt: "Baixa vitalidade. Repouse muito.", en: "Low vitality. Rest a lot.", es: "Baja vitalidad. Reposa mucho.", hi: "कम जीवन शक्ति। बहुत आराम करें।" },
    finance: { pt: "Perdas possíveis. Seja conservador.", en: "Possible losses. Be conservative.", es: "Pérdidas posibles. Sé conservador.", hi: "संभावित नुकसान। रूढ़िवादी बनें।" },
  },
  {
    number: 24, name: "fu", chinese: "復", binary: "000001", upperTrigram: "earth", lowerTrigram: "thunder",
    displayName: { pt: "O Retorno", en: "Return", es: "El Retorno", hi: "वापसी" },
    judgment: { pt: "Sucesso. O caminho se abre novamente.", en: "Success. The path opens again.", es: "Éxito. El camino se abre de nuevo.", hi: "सफलता। मार्ग फिर से खुलता है।" },
    image: { pt: "O trovão dentro da terra.", en: "Thunder within the earth.", es: "El trueno dentro de la tierra.", hi: "पृथ्वी के भीतर गड़गड़ाहट।" },
    advice: { pt: "Retorne às suas raízes e princípios.", en: "Return to your roots and principles.", es: "Regresa a tus raíces y principios.", hi: "अपनी जड़ों और सिद्धांतों पर लौटें।" },
    love: { pt: "Reconciliação e novos começos.", en: "Reconciliation and new beginnings.", es: "Reconciliación y nuevos comienzos.", hi: "सुलह और नई शुरुआत।" },
    career: { pt: "Recomeço promissor em projetos.", en: "Promising restart in projects.", es: "Recomienzo prometedor en proyectos.", hi: "प्रोजेक्ट्स में आशाजनक पुनरारंभ।" },
    health: { pt: "Recuperação de energia vital.", en: "Recovery of vital energy.", es: "Recuperación de energía vital.", hi: "महत्वपूर्ण ऊर्जा की रिकवरी।" },
    finance: { pt: "Recuperação de perdas anteriores.", en: "Recovery of previous losses.", es: "Recuperación de pérdidas anteriores.", hi: "पिछले नुकसान की भरपाई।" },
  },
  {
    number: 25, name: "wu wang", chinese: "無妄", binary: "100111", upperTrigram: "heaven", lowerTrigram: "thunder",
    displayName: { pt: "A Inocência", en: "Innocence", es: "La Inocencia", hi: "मासूमियत" },
    judgment: { pt: "Sucesso supremo se houver retidão.", en: "Supreme success if there is rectitude.", es: "Éxito supremo si hay rectitud.", hi: "यदि सत्यनिष्ठा हो तो परम सफलता।" },
    image: { pt: "O trovão sob o céu.", en: "Thunder under the sky.", es: "El trueno bajo el cielo.", hi: "आकाश के नीचे गड़गड़ाहट।" },
    advice: { pt: "Aja com espontaneidade e verdade.", en: "Act with spontaneity and truth.", es: "Actúa con espontaneidad y verdad.", hi: "सहजता और सच्चाई के साथ कार्य करें।" },
    love: { pt: "Amor puro e desinteressado.", en: "Pure and selfless love.", es: "Amor puro y desinteresado.", hi: "शुद्ध और निस्वार्थ प्रेम।" },
    career: { pt: "Siga seu caminho com integridade.", en: "Follow your path with integrity.", es: "Sigue tu camino con integridad.", hi: "ईमानदारी के साथ अपने मार्ग पर चलें।" },
    health: { pt: "Saúde natural e vigorosa.", en: "Natural and vigorous health.", es: "Salud natural y vigorosa.", hi: "प्राकृतिक और जोरदार स्वास्थ्य।" },
    finance: { pt: "Ganhos inesperados por mérito.", en: "Unexpected gains by merit.", es: "Ganancias inesperadas por mérito.", hi: "योग्यता के आधार पर अप्रत्याशित लाभ।" },
  },
  {
    number: 26, name: "da chu", chinese: "大畜", binary: "111001", upperTrigram: "mountain", lowerTrigram: "heaven",
    displayName: { pt: "Grande Acúmulo", en: "Great Accumulation", es: "Gran Acúmulo", hi: "बड़ा संचय" },
    judgment: { pt: "Perseverança favorece. Fortuna.", en: "Perseverance brings fortune.", es: "La perseverancia trae fortuna.", hi: "दृढ़ता भाग्य लाती है।" },
    image: { pt: "O céu dentro da montanha.", en: "The sky within the mountain.", es: "El cielo dentro de la montaña.", hi: "पहाड़ के भीतर आकाश।" },
    advice: { pt: "Acumule força e sabedoria.", en: "Accumulate strength and wisdom.", es: "Acumula fuerza y sabiduría.", hi: "शक्ति और ज्ञान संचित करें।" },
    love: { pt: "Relacionamentos sólidos e maduros.", en: "Solid and mature relationships.", es: "Relaciones sólidas y maduras.", hi: "ठोस और परिपक्व रिश्ते।" },
    career: { pt: "Grande potencial de liderança.", en: "Great leadership potential.", es: "Gran potencial de liderazgo.", hi: "महान नेतृत्व क्षमता।" },
    health: { pt: "Reserva de energia física.", en: "Reserve of physical energy.", es: "Reserva de energía física.", hi: "शारीरिक ऊर्जा का संचय।" },
    finance: { pt: "Grande acúmulo de riqueza.", en: "Great accumulation of wealth.", es: "Gran acumulación de riqueza.", hi: "धन का बड़ा संचय।" },
  },
  {
    number: 27, name: "yi", chinese: "頤", binary: "100001", upperTrigram: "mountain", lowerTrigram: "thunder",
    displayName: { pt: "A Nutrição", en: "Nourishment", es: "La Nutrición", hi: "पोषण" },
    judgment: { pt: "Observe a nutrição e o que se busca.", en: "Observe nourishment and what is sought.", es: "Observa la nutrición y lo que se busca.", hi: "पोषण और जो मांगा गया है उसका निरीक्षण करें।" },
    image: { pt: "Trovão na base da montanha.", en: "Thunder at the base of the mountain.", es: "Trueno en la base de la montaña.", hi: "पहाड़ के आधार पर गड़गड़ाहट।" },
    advice: { pt: "Cuide do que você consome.", en: "Care for what you consume.", es: "Cuida lo que consumes.", hi: "आप जो उपभोग करते हैं उसका ख्याल रखें।" },
    love: { pt: "Nutra o afeto e o cuidado mútuo.", en: "Nurture affection and mutual care.", es: "Nutre el afecto y el cuidado mutuo.", hi: "स्नेह और आपसी देखभाल का पोषण करें।" },
    career: { pt: "Desenvolva suas habilidades.", en: "Develop your skills.", es: "Desarrolla tus habilidades.", hi: "अपने कौशल का विकास करें।" },
    health: { pt: "Atenção à dieta e digestão.", en: "Attention to diet and digestion.", es: "Atención a la dieta y la digestión.", hi: "आहार और पाचन पर ध्यान दें।" },
    finance: { pt: "Invista no seu crescimento pessoal.", en: "Invest in your personal growth.", es: "Invierte en tu crecimiento personal.", hi: "अपने व्यक्तिगत विकास में निवेश करें।" },
  },
  {
    number: 28, name: "da guo", chinese: "大過", binary: "011110", upperTrigram: "lake", lowerTrigram: "wind",
    displayName: { pt: "Grande Excesso", en: "Great Preponderance", es: "Gran Exceso", hi: "महान प्रचुरता" },
    judgment: { pt: "A viga mestre verga. Favorece ação.", en: "The ridgepole bends. Favors action.", es: "La viga maestra se dobla. Favorece la acción.", hi: "मुख्य शहतीर झुकती है। कार्रवाई का पक्ष लेती है।" },
    image: { pt: "O lago submerge as árvores.", en: "The lake submerges the trees.", es: "El lago sumerge los árboles.", hi: "झील पेड़ों को डुबो देती है।" },
    advice: { pt: "Enfrente situações excepcionais.", en: "Face exceptional situations.", es: "Enfrenta situaciones excepcionales.", hi: "असाधारण स्थितियों का सामना करें।" },
    love: { pt: "Paixão intensa e transbordante.", en: "Intense and overflowing passion.", es: "Pasión intensa y desbordante.", hi: "तीव्र और उमड़ता हुआ जुनून।" },
    career: { pt: "Decisões cruciais sob pressão.", en: "Crucial decisions under pressure.", es: "Decisiones cruciales bajo presión.", hi: "दबाव में महत्वपूर्ण निर्णय।" },
    health: { pt: "Cuidado com esgotamento físico.", en: "Careful with physical exhaustion.", es: "Cuidado con el agotamiento físico.", hi: "शारीरिक थकावट से सावधान रहें।" },
    finance: { pt: "Risco alto por grandes ganhos.", en: "High risk for great gains.", es: "Alto riesgo por grandes ganancias.", hi: "बड़े लाभ के लिए उच्च जोखिम।" },
  },
  {
    number: 29, name: "kan", chinese: "坎", binary: "010010", upperTrigram: "water", lowerTrigram: "water",
    displayName: { pt: "O Abismo", en: "The Abysmal", es: "El Abismo", hi: "अथाह" },
    judgment: { pt: "Sinceridade traz sucesso no coração.", en: "Sincerity brings success in the heart.", es: "La sinceridad trae éxito en el corazón.", hi: "सच्चाई दिल में सफलता लाती है।" },
    image: { pt: "Água flui ininterruptamente.", en: "Water flows uninterruptedly.", es: "El agua fluye ininterrumpidamente.", hi: "पानी लगातार बहता है।" },
    advice: { pt: "Mantenha a coragem no perigo.", en: "Maintain courage in danger.", es: "Mantén el valor en el peligro.", hi: "खतरे में साहस बनाए रखें।" },
    love: { pt: "Emoções profundas e desafiadoras.", en: "Deep and challenging emotions.", es: "Emociones profundas y desafiantes.", hi: "गहरी और चुनौतीपूर्ण भावनाएं।" },
    career: { pt: "Navegue obstáculos com fluidez.", en: "Navigate obstacles with fluidity.", es: "Navega obstáculos con fluidez.", hi: "तरलता के साथ बाधाओं को पार करें।" },
    health: { pt: "Sistema circulatório e rins.", en: "Circulatory system and kidneys.", es: "Sistema circulatorio y riñones.", hi: "परिसंचरण तंत्र और गुर्दे।" },
    finance: { pt: "Período de cautela extrema.", en: "Period of extreme caution.", es: "Periodo de extrema cautela.", hi: "अत्यधिक सावधानी की अवधि।" },
  },
  {
    number: 30, name: "li", chinese: "離", binary: "101101", upperTrigram: "fire", lowerTrigram: "fire",
    displayName: { pt: "O Aderente", en: "The Clinging", es: "Lo Adherente", hi: "चिपकने वाला" },
    judgment: { pt: "Perseverança favorece. Sucesso.", en: "Perseverance brings success.", es: "La perseverancia trae éxito.", hi: "दृढ़ता सफलता लाती है।" },
    image: { pt: "O fogo brilha duplicado.", en: "Fire shines doubled.", es: "El fuego brilla duplicado.", hi: "आग दोगुनी चमकती है।" },
    advice: { pt: "Busque clareza e entendimento.", en: "Seek clarity and understanding.", es: "Busca claridad y entendimiento.", hi: "स्पष्टता और समझ की तलाश करें।" },
    love: { pt: "Clareza nos afetos e brilho.", en: "Clarity in affections and radiance.", es: "Claridad en los afectos y brillo.", hi: "स्नेह और चमक में स्पष्टता।" },
    career: { pt: "Sucesso sob os holofotes.", en: "Success under the spotlight.", es: "Éxito bajo los reflectores.", hi: "सुर्खियों में सफलता।" },
    health: { pt: "Cuidado com a visão e febres.", en: "Care for vision and fevers.", es: "Cuidado con la visión y fiebres.", hi: "दृष्टि और बुखार का ख्याल रखें।" },
    finance: { pt: "Ganhos através de inteligência.", en: "Gains through intelligence.", es: "Ganancias a través de la inteligencia.", hi: "बुद्धिमत्ता के माध्यम से लाभ।" },
  },
  {
    number: 31, name: "xian", chinese: "咸", binary: "011100", upperTrigram: "lake", lowerTrigram: "mountain",
    displayName: { pt: "A Influência", en: "Influence", es: "La Influencia", hi: "प्रभाव" },
    judgment: { pt: "Sucesso. Tomar uma esposa traz fortuna.", en: "Success. Taking a wife brings fortune.", es: "Éxito. Tomar una esposa trae fortuna.", hi: "सफलता। पत्नी को स्वीकार करना भाग्य लाता है।" },
    image: { pt: "O lago sobre a montanha.", en: "The lake over the mountain.", es: "El lago sobre la montaña.", hi: "पहाड़ पर झील।" },
    advice: { pt: "Abra-se para influências sutis.", en: "Open up to subtle influences.", es: "Ábrete a influencias sutiles.", hi: "सूक्ष्म प्रभावों के लिए तत्पर रहें।" },
    love: { pt: "Atração mútua e sintonia.", en: "Mutual attraction and harmony.", es: "Atracción mutua y sintonía.", hi: "पारस्परिक आकर्षण और सद्भाव।" },
    career: { pt: "Conquiste parceiros com carisma.", en: "Win partners with charisma.", es: "Conquista socios con carisma.", hi: "करिश्मे के साथ साझेदारों को जीतें।" },
    health: { pt: "Equilíbrio de fluidos e nervos.", en: "Fluid and nerve balance.", es: "Equilibrio de fluidos y nervios.", hi: "तरल और तंत्रिका संतुलन।" },
    finance: { pt: "Negociações harmoniosas.", en: "Harmonious negotiations.", es: "Negociaciones armoniosas.", hi: "सौहार्दपूर्ण बातचीत।" },
  },
  {
    number: 32, name: "heng", chinese: "恆", binary: "001011", upperTrigram: "thunder", lowerTrigram: "wind",
    displayName: { pt: "A Duração", en: "Duration", es: "La Duración", hi: "अवधि" },
    judgment: { pt: "Sucesso. Perseverança traz fortuna.", en: "Success. Perseverance brings fortune.", es: "Éxito. La perseverancia trae fortuna.", hi: "सफलता। दृढ़ता भाग्य लाती है।" },
    image: { pt: "Trovão e vento: Duração.", en: "Thunder and wind: Duration.", es: "Trueno y viento: Duración.", hi: "गड़गड़ाहट और हवा: अवधि।" },
    advice: { pt: "Mantenha a constância e o foco.", en: "Maintain constancy and focus.", es: "Mantén la constancia y el enfoque.", hi: "निरंतरता और फोकस बनाए रखें।" },
    love: { pt: "Estabilidade e compromisso longo.", en: "Stability and long commitment.", es: "Estabilidad y compromiso largo.", hi: "स्थिरता और लंबी प्रतिबद्धता।" },
    career: { pt: "Sucesso através da persistência.", en: "Success through persistence.", es: "Éxito a través de la persistencia.", hi: "दृढ़ता के माध्यम से सफलता।" },
    health: { pt: "Mantenha rotinas saudáveis.", en: "Maintain healthy routines.", es: "Mantén rutinas saludables.", hi: "स्वस्थ दिनचर्या बनाए रखें।" },
    finance: { pt: "Investimentos sólidos e duradouros.", en: "Solid and lasting investments.", es: "Inversiones sólidas y duraderas.", hi: "ठोस और स्थायी निवेश।" },
  },
  {
    number: 33, name: "dun", chinese: "遯", binary: "001111", upperTrigram: "heaven", lowerTrigram: "mountain",
    displayName: { pt: "A Retirada", en: "Retreat", es: "La Retirada", hi: "पीछे हटना" },
    judgment: { pt: "Sucesso em pequenas coisas. Recue.", en: "Success in small things. Retreat.", es: "Éxito en pequeñas cosas. Retirada.", hi: "छोटी-छोटी बातों में सफलता। पीछे हटें।" },
    image: { pt: "A montanha sob o céu se retira.", en: "Mountain under the sky retreats.", es: "La montaña bajo el cielo se retira.", hi: "आकाश के नीचे पहाड़ पीछे हटता है।" },
    advice: { pt: "Saiba quando parar e se retirar.", en: "Know when to stop and retreat.", es: "Sabe cuándo parar y retirarte.", hi: "जानें कि कब रुकना और पीछे हटना है।" },
    love: { pt: "Dê espaço para o outro e para si.", en: "Give space to others and yourself.", es: "Da espacio al otro y a ti mismo.", hi: "दूसरों को और खुद को जगह दें।" },
    career: { pt: "Evite conflitos, retire-se um pouco.", en: "Avoid conflict, withdraw a bit.", es: "Evita conflictos, retírate un poco.", hi: "विवादों से बचें, थोड़ा पीछे हटें।" },
    health: { pt: "Recolhimento para cura interior.", en: "Retreat for inner healing.", es: "Retirada para sanación interior.", hi: "आंतरिक उपचार के लिए पीछे हटना।" },
    finance: { pt: "Proteja seu capital, não invista agora.", en: "Protect capital, do not invest now.", es: "Protege tu capital, no inviertas ahora.", hi: "अपनी पूंजी की रक्षा करें, अभी निवेश न करें।" },
  },
  {
    number: 34, name: "da zhuang", chinese: "大壯", binary: "111100", upperTrigram: "thunder", lowerTrigram: "heaven",
    displayName: { pt: "O Poder do Grande", en: "The Power of the Great", es: "El Poder de lo Grande", hi: "महान की शक्ति" },
    judgment: { pt: "Perseverança favorece o grande sucesso.", en: "Perseverance favors great success.", es: "La perseverancia favorece el gran éxito.", hi: "दृढ़ता महान सफलता का पक्ष लेती है।" },
    image: { pt: "Trovão no céu: Grande poder.", en: "Thunder in the sky: Great power.", es: "Trueno en el cielo: Gran poder.", hi: "आकाश में गड़गड़ाहट: महान शक्ति।" },
    advice: { pt: "Use seu poder com sabedoria.", en: "Use your power with wisdom.", es: "Usa tu poder con sabiduría.", hi: "अपनी शक्ति का बुद्धिमानी से उपयोग करें।" },
    love: { pt: "Paixão avassaladora e força.", en: "Overwhelming passion and strength.", es: "Pasión arrolladora y fuerza.", hi: "जबरदस्त जुनून और ताकत।" },
    career: { pt: "Grande influência profissional.", en: "Great professional influence.", es: "Gran influencia profesional.", hi: "महान पेशेवर प्रभाव।" },
    health: { pt: "Muita força física disponível.", en: "Much physical strength available.", es: "Mucha fuerza física disponible.", hi: "बहुत सारी शारीरिक शक्ति उपलब्ध है।" },
    finance: { pt: "Grande expansão financeira.", en: "Great financial expansion.", es: "Gran expansión financiera.", hi: "महान वित्तीय विस्तार।" },
  },
  {
    number: 35, name: "jin", chinese: "晉", binary: "000101", upperTrigram: "fire", lowerTrigram: "earth",
    displayName: { pt: "O Progresso", en: "Progress", es: "El Progresso", hi: "प्रगति" },
    judgment: { pt: "Progresso rápido. Fortuna.", en: "Rapid progress. Fortune.", es: "Progreso rápido. Fortuna.", hi: "तेजी से प्रगति। भाग्य।" },
    image: { pt: "O sol nasce sobre a terra.", en: "The sun rises over the earth.", es: "El sol nace sobre la tierra.", hi: "पृथ्वी पर सूर्य उदय होता है।" },
    advice: { pt: "Avance com confiança e clareza.", en: "Advance with confidence and clarity.", es: "Avanza con confianza y claridad.", hi: "आत्मविश्वास और स्पष्टता के साथ आगे बढ़ें।" },
    love: { pt: "Relacionamentos sobem de nível.", en: "Relationships level up.", es: "Las relaciones suben de nivel.", hi: "रिश्ते अगले स्तर पर पहुँचते हैं।" },
    career: { pt: "Promoções e sucesso visível.", en: "Promotions and visible success.", es: "Ascensos y éxito visible.", hi: "पदोन्नति और दृश्य सफलता।" },
    health: { pt: "Aumento da vitalidade diária.", en: "Increase in daily vitality.", es: "Aumento de la vitalidad diaria.", hi: "दैनिक जीवन शक्ति में वृद्धि।" },
    finance: { pt: "Ganhos claros e crescentes.", en: "Clear and increasing gains.", es: "Ganancias claras y crecientes.", hi: "स्पष्ट और बढ़ता हुआ लाभ।" },
  },
  {
    number: 36, name: "ming yi", chinese: "明夷", binary: "101000", upperTrigram: "earth", lowerTrigram: "fire",
    displayName: { pt: "O Obscurecer da Luz", en: "Darkening of the Light", es: "El Oscurecimiento de la Luz", hi: "प्रकाश का धुंधला होना" },
    judgment: { pt: "Perseverança na adversidade favorece.", en: "Perseverance in adversity furthers.", es: "La perseverancia en la adversidad favorece.", hi: "प्रतिकूल परिस्थितियों में दृढ़ता लाभ देती है।" },
    image: { pt: "O sol se põe sob a terra.", en: "The sun sets under the earth.", es: "El sol se oculta bajo la tierra.", hi: "सूरज धरती के नीचे डूब जाता है।" },
    advice: { pt: "Oculte sua luz no momento difícil.", en: "Hide your light in difficult times.", es: "Oculta tu luz en momentos difíciles.", hi: "मुश्किल समय में अपनी रोशनी छिपाएं।" },
    love: { pt: "Discrição e segredos nos afetos.", en: "Discretion and secrets in affection.", es: "Discreción y secretos en los afectos.", hi: "स्नेह में विवेक और रहस्य।" },
    career: { pt: "Mantenha discrição no trabalho.", en: "Keep low profile at work.", es: "Mantén un perfil bajo en el trabajo.", hi: "काम पर कम प्रोफ़ाइल रखें।" },
    health: { pt: "Cansaço visual ou emocional.", en: "Visual or emotional fatigue.", es: "Cansancio visual o emocional.", hi: "दृश्य या भावनात्मक थकान।" },
    finance: { pt: "Proteja seus ativos da vista alheia.", en: "Protect assets from others' sight.", es: "Protege tus activos de la vista ajena.", hi: "अपनी संपत्ति को दूसरों की नज़रों से बचाएं।" },
  },
  {
    number: 37, name: "jia ren", chinese: "家人", binary: "101011", upperTrigram: "wind", lowerTrigram: "fire",
    displayName: { pt: "O Clã", en: "The Family", es: "El Clan", hi: "परिवार" },
    judgment: { pt: "Perseverança da mulher traz fortuna.", en: "Perseverance of the woman brings fortune.", es: "La perseverancia de la mujer trae fortuna.", hi: "महिला की दृढ़ता भाग्य लाती है।" },
    image: { pt: "O vento sopra de dentro do fogo.", en: "Wind blows from within the fire.", es: "El viento sopla desde dentro del fuego.", hi: "आग के भीतर से हवा चलती है।" },
    advice: { pt: "Harmonize sua casa e família.", en: "Harmonize your home and family.", es: "Armoniza tu hogar y familia.", hi: "अपने घर और परिवार में सामंजस्य बिठाएं।" },
    love: { pt: "União familiar e amor sólido.", en: "Family union and solid love.", es: "Unión familiar y amor sólido.", hi: "पारिवारिक मिलन और ठोस प्रेम।" },
    career: { pt: "Bons resultados em empresas familiares.", en: "Good results in family businesses.", es: "Buenos resultados en empresas familiares.", hi: "पारिवारिक व्यवसायों में अच्छे परिणाम।" },
    health: { pt: "Conforto térmico e digestivo.", en: "Thermal and digestive comfort.", es: "Confort térmico y digestivo.", hi: "थर्मल और पाचन आराम।" },
    finance: { pt: "Gestão do orçamento doméstico.", en: "Managing the domestic budget.", es: "Gestión del presupuesto doméstico.", hi: "घरेलू बजट का प्रबंधन।" },
  },
  {
    number: 38, name: "kui", chinese: "睽", binary: "110101", upperTrigram: "fire", lowerTrigram: "lake",
    displayName: { pt: "A Oposição", en: "Opposition", es: "La Oposición", hi: "विरोध" },
    judgment: { pt: "Sucesso em pequenas questões.", en: "Success in small matters.", es: "Éxito en asuntos pequeños.", hi: "छोटे मामलों में सफलता।" },
    image: { pt: "Fogo acima, lago abaixo.", en: "Fire above, lake below.", es: "Fuego arriba, lago abajo.", hi: "ऊपर आग, नीचे झील।" },
    advice: { pt: "Aprenda com o que é diferente.", en: "Learn from what is different.", es: "Aprende de lo que es diferente.", hi: "जो अलग है उससे सीखें।" },
    love: { pt: "Diferenças que ensinam paciência.", en: "Differences that teach patience.", es: "Diferencias que enseñan paciencia.", hi: "मतभेद जो धैर्य सिखाते हैं।" },
    career: { pt: "Harmonize interesses divergentes.", en: "Harmonize divergent interests.", es: "Armoniza intereses divergentes.", hi: "अलग-अलग हितों में सामंजस्य बिठाएं।" },
    health: { pt: "Equilíbrio de polaridades no corpo.", en: "Balance of polarities in the body.", es: "Equilibrio de polaridades en el cuerpo.", hi: "शरीर में ध्रुवीयताओं का संतुलन।" },
    finance: { pt: "Cuidado com divergências em sócios.", en: "Careful with partner divergences.", es: "Cuidado con divergencias entre socios.", hi: "साझेदारों के मतभेदों से सावधान रहें।" },
  },
  {
    number: 39, name: "jian", chinese: "蹇", binary: "001010", upperTrigram: "water", lowerTrigram: "mountain",
    displayName: { pt: "A Obstrução", en: "Obstruction", es: "La Obstrucción", hi: "रुकावट" },
    judgment: { pt: "Favorece o sudoeste. O nordeste não.", en: "Southwest favors. Northeast does not.", es: "El suroeste favorece. El noreste no.", hi: "दक्षिण-पश्चिम पक्ष में है। उत्तर-पूर्व नहीं।" },
    image: { pt: "Água sobre a montanha: Dificuldade.", en: "Water over the mountain: Difficulty.", es: "Agua sobre la montaña: Dificultad.", hi: "पहाड़ पर जल: कठिनाई।" },
    advice: { pt: "Pare e peça conselho agora.", en: "Stop and seek advice now.", es: "Para y pide consejo ahora.", hi: "रुकें और अभी सलाह लें।" },
    love: { pt: "Obstáculos emocionais no caminho.", en: "Emotional obstacles in the way.", es: "Obstáculos emocionales en el camino.", hi: "रास्ते में भावनात्मक बाधाएँ।" },
    career: { pt: "Aguarde o momento para agir.", en: "Wait for the moment to act.", es: "Espera el momento para actuar.", hi: "कार्य करने के लिए समय का इंतज़ार करें।" },
    health: { pt: "Cuidado com ossos e pernas.", en: "Care for bones and legs.", es: "Cuidado con huesos y piernas.", hi: "हड्डियों और पैरों का ख्याल रखें।" },
    finance: { pt: "Não force ganhos agora.", en: "Do not force gains now.", es: "No fuerces ganancias ahora.", hi: "अभी लाभ पर दबाव न डालें।" },
  },
  {
    number: 40, name: "xie", chinese: "解", binary: "010011", upperTrigram: "thunder", lowerTrigram: "water",
    displayName: { pt: "A Liberação", en: "Deliverance", es: "La Liberación", hi: "मुक्ति" },
    judgment: { pt: "Favorece o sudoeste. Sucesso rápido.", en: "Southwest favors. Quick success.", es: "El suroeste favorece. Éxito rápido.", hi: "दक्षिण-पश्चिम पक्ष में है। त्वरित सफलता।" },
    image: { pt: "Trovão e chuva trazem liberação.", en: "Thunder and rain bring deliverance.", es: "Trueno y lluvia traen liberación.", hi: "गड़गड़ाहट और बारिश मुक्ति लाती है।" },
    advice: { pt: "Resolva pendências e siga em frente.", en: "Resolve pending issues and move on.", es: "Resuelve pendientes y sigue adelante.", hi: "लंबित मुद्दों को सुलझाएं और आगे बढ़ें।" },
    love: { pt: "Perdão e alívio emocional.", en: "Forgiveness and emotional relief.", es: "Perdón y alivio emocional.", hi: "क्षमा और भावनात्मक राहत।" },
    career: { pt: "Problemas resolvidos rapidamente.", en: "Problems solved quickly.", es: "Problemas resueltos rápidamente.", hi: "समस्याएं जल्दी हल हो गईं।" },
    health: { pt: "Sensação de alívio e renovação.", en: "Sense of relief and renewal.", es: "Sensación de alivio y renovación.", hi: "राहत और नवीनीकरण का अहसास।" },
    finance: { pt: "Liberação de recursos travados.", en: "Release of locked resources.", es: "Liberación de recursos trabados.", hi: "बंद संसाधनों की मुक्ति।" },
  },
  {
    number: 41, name: "sun", chinese: "損", binary: "110001", upperTrigram: "mountain", lowerTrigram: "lake",
    displayName: { pt: "A Diminuição", en: "Decrease", es: "La Disminución", hi: "कमी" },
    judgment: { pt: "Sinceridade traz fortuna suprema. Favorece a ação.", en: "Sincerity brings supreme fortune. Favors action.", es: "La sinceridad trae fortuna suprema. Favorece la acción.", hi: "सच्चाई परम भाग्य लाती है। कार्रवाई का पक्ष लेती है।" },
    image: { pt: "O lago na base da montanha diminui.", en: "The lake at the base of the mountain decreases.", es: "El lago en la base de la montaña disminuye.", hi: "पहाड़ के आधार पर झील कम हो जाती है।" },
    advice: { pt: "Simplifique sua vida e reduza excessos.", en: "Simplify your life and reduce excesses.", es: "Simplifica tu vida y reduce excesos.", hi: "अपने जीवन को सरल बनाएं और अधिकता को कम करें।" },
    love: { pt: "Abnegação fortalece o laço afetivo.", en: "Selflessness strengthens the bond.", es: "La abnegación fortalece el vínculo afectivo.", hi: "निस्वार्थता रिश्ते को मजबूत करती है।" },
    career: { pt: "Corte gastos desnecessários no trabalho.", en: "Cut unnecessary expenses at work.", es: "Corta gastos innecesarios en el trabajo.", hi: "काम पर अनावश्यक खर्च कम करें।" },
    health: { pt: "Dieta leve e desintoxicação.", en: "Light diet and detox.", es: "Dieta ligera y desintoxicación.", hi: "हल्का आहार और विषहरण।" },
    finance: { pt: "Redução de custos leva a lucros futuros.", en: "Cost reduction leads to future profits.", es: "La reducción de costos lleva a lucros futuros.", hi: "लागत में कमी भविष्य के मुनाफे की ओर ले जाती है।" },
  },
  {
    number: 42, name: "yi", chinese: "益", binary: "100011", upperTrigram: "wind", lowerTrigram: "thunder",
    displayName: { pt: "O Aumento", en: "Increase", es: "El Aumento", hi: "वृद्धि" },
    judgment: { pt: "Favorece a ação e atravessar a grande água.", en: "Favors action and crossing the great water.", es: "Favorece la acción y cruzar la gran agua.", hi: "कार्रवाई और महान जल को पार करना अनुकूल है।" },
    image: { pt: "Vento e trovão: O aumento.", en: "Wind and thunder: Increase.", es: "Viento y trueno: El aumento.", hi: "हवा और गड़गड़ाहट: वृद्धि।" },
    advice: { pt: "Aproveite a maré de crescimento agora.", en: "Take advantage of the growth tide now.", es: "Aprovecha la marea de crecimiento ahora.", hi: "अब विकास की लहर का लाभ उठाएं।" },
    love: { pt: "Expansão da felicidade e do compromisso.", en: "Expansion of happiness and commitment.", es: "Expansión de la felicidad y el compromiso.", hi: "खुशी और प्रतिबद्धता का विस्तार।" },
    career: { pt: "Novas oportunidades e progresso rápido.", en: "New opportunities and rapid progress.", es: "Nuevas oportunidades y rápido progreso.", hi: "नए अवसर और तीव्र प्रगति।" },
    health: { pt: "Muita vitalidade e energia de vida.", en: "High vitality and life energy.", es: "Mucha vitalidad y energía de vida.", hi: "उच्च जीवन शक्ति और जीवन ऊर्जा।" },
    finance: { pt: "Ganhos significativos em investimentos.", en: "Significant gains in investments.", es: "Ganancias significativas en inversiones.", hi: "निवेश में महत्वपूर्ण लाभ।" },
  },
  {
    number: 43, name: "guai", chinese: "夬", binary: "111110", upperTrigram: "lake", lowerTrigram: "heaven",
    displayName: { pt: "A Resolução", en: "Break-through", es: "La Resolución", hi: "संकल्प" },
    judgment: { pt: "Deve-se anunciar a verdade resolutamente.", en: "Truth must be announced resolutely.", es: "Se debe anunciar la verdad resueltamente.", hi: "सच्चाई की घोषणा दृढ़ता के साथ की जानी चाहिए।" },
    image: { pt: "O lago sobe ao céu: Resolução.", en: "The lake rises to the sky: Resolution.", es: "El lago sube al cielo: Resolución.", hi: "झील आकाश तक पहुँचती है: संकल्प।" },
    advice: { pt: "Tome uma decisão definitiva com clareza.", en: "Make a final decision with clarity.", es: "Toma una decisión definitiva con claridad.", hi: "स्पष्टता के साथ अंतिम निर्णय लें।" },
    love: { pt: "Definição de status no relacionamento.", en: "Status definition in relationships.", es: "Definición del estatus de la relación.", hi: "रिश्ते की स्थिति की परिभाषा।" },
    career: { pt: "Ruptura com o que é ineficiente.", en: "Break away from inefficiency.", es: "Ruptura con lo que es ineficiente.", hi: "अक्षमता से छुटकारा पाएं।" },
    health: { pt: "Remoção de toxinas e tensões.", en: "Removal of toxins and tensions.", es: "Eliminación de toxinas y tensiones.", hi: "विषाक्त पदार्थों और तनाव को दूर करना।" },
    finance: { pt: "Liquidação de dívidas e decisões.", en: "Debt settlement and decisions.", es: "Liquidación de deudas y decisiones.", hi: "ऋण निपटान और निर्णय।" },
  },
  {
    number: 44, name: "gou", chinese: "姤", binary: "011111", upperTrigram: "heaven", lowerTrigram: "wind",
    displayName: { pt: "O Ir ao Encontro", en: "Coming to Meet", es: "El Ir al Encuentro", hi: "मिलने आना" },
    judgment: { pt: "A mulher é poderosa. Não se deve casar.", en: "The woman is powerful. One should not marry.", es: "La mujer es poderosa. No se debe casar.", hi: "स्त्री शक्तिशाली है। विवाह नहीं करना चाहिए।" },
    image: { pt: "O vento sopra sob o céu.", en: "The wind blows under the sky.", es: "El viento sopla bajo el cielo.", hi: "आकाश के नीचे हवा चलती है।" },
    advice: { pt: "Cuidado com influências sedutoras.", en: "Watch out for seductive influences.", es: "Cuidado con influencias seductoras.", hi: "मोहक प्रभावों से सावधान रहें।" },
    love: { pt: "Atração perigosa ou passageira.", en: "Dangerous or fleeting attraction.", es: "Atracción peligrosa o pasajera.", hi: "खतरनाक या क्षणिक आकर्षण।" },
    career: { pt: "Influências ocultas no escritório.", en: "Hidden influences at the office.", es: "Influencias ocultas en la oficina.", hi: "कार्यालय में छिपे हुए प्रभाव।" },
    health: { pt: "Atenção ao sistema hormonal.", en: "Attention to hormonal system.", es: "Atención al sistema hormonal.", hi: "हार्मोनल तंत्र पर ध्यान दें।" },
    finance: { pt: "Propostas atraentes, mas arriscadas.", en: "Attractive but risky proposals.", es: "Propuestas atractivas pero arrisgadas.", hi: "आकर्षक लेकिन जोखिम भरे प्रस्ताव।" },
  },
  {
    number: 45, name: "cui", chinese: "萃", binary: "011000", upperTrigram: "lake", lowerTrigram: "earth",
    displayName: { pt: "A Reunião", en: "Gathering Together", es: "La Reunión", hi: "एकत्र होना" },
    judgment: { pt: "Sucesso. O rei se aproxima do templo.", en: "Success. The king approaches the temple.", es: "Éxito. El rey se acerca al templo.", hi: "सफलता। राजा मंदिर की ओर बढ़ता है।" },
    image: { pt: "O lago sobre a terra: Reunião.", en: "The lake over the earth: Gathering.", es: "El lago sobre la tierra: Reunión.", hi: "पृथ्वी पर झील: एकत्रीकरण।" },
    advice: { pt: "Unifique pessoas em torno de metas.", en: "Unify people around goals.", es: "Une a las personas en torno a metas.", hi: "लोगों को लक्ष्यों के प्रति एकजुट करें।" },
    love: { pt: "Celebração e encontros familiares.", en: "Celebration and family gatherings.", es: "Celebración y encuentros familiares.", hi: "उत्सव और पारिवारिक मिलन।" },
    career: { pt: "Sucesso em congressos e grupos.", en: "Success in congresses and groups.", es: "Éxito en congresos y grupos.", hi: "सम्मेलनों और समूहों में सफलता।" },
    health: { pt: "Saúde através do bem-estar social.", en: "Health through social well-being.", es: "Salud a través del bienestar social.", hi: "सामाजिक कल्याण के माध्यम से स्वास्थ्य।" },
    finance: { pt: "Acúmulo de riqueza coletiva.", en: "Accumulation of collective wealth.", es: "Acumulación de riqueza colectiva.", hi: "सामूहिक धन का संचय।" },
  },
  {
    number: 46, name: "sheng", chinese: "升", binary: "000110", upperTrigram: "earth", lowerTrigram: "wind",
    displayName: { pt: "A Ascensão", en: "Pushing Upward", es: "La Ascensión", hi: "ऊपर की ओर धकेलना" },
    judgment: { pt: "Sucesso sublime. Favorece a ação agora.", en: "Sublime success. Favors action now.", es: "Éxito sublime. Favorece la acción ahora.", hi: "उदात्त सफलता। अब कार्रवाई का पक्ष लेता है।" },
    image: { pt: "A madeira cresce dentro da terra.", en: "Wood grows within the earth.", es: "La madera crece dentro de la tierra.", hi: "पृथ्वी के भीतर लकड़ी उगती है।" },
    advice: { pt: "Suba passo a passo com paciência.", en: "Go up step by step with patience.", es: "Sube paso a paso con paciencia.", hi: "धैर्य के साथ कदम दर कदम आगे बढ़ें।" },
    love: { pt: "Relação que amadurece e cresce.", en: "Relationship that matures and grows.", es: "Relación que madura y crece.", hi: "रिश्ता जो परिपक्व होता है और बढ़ता है।" },
    career: { pt: "Promoção gradual e merecida.", en: "Gradual and deserved promotion.", es: "Ascenso gradual y merecido.", hi: "धीरे-धीरे और उचित पदोन्नति।" },
    health: { pt: "Crescimento da força vital.", en: "Growth of vital force.", es: "Crecimiento de la fuerza vital.", hi: "जीवन शक्ति का विकास।" },
    finance: { pt: "Crescimento constante do capital.", en: "Steady growth of capital.", es: "Crecimiento constante del capital.", hi: "पूंजी की निरंतर वृद्धि।" },
  },
  {
    number: 47, name: "kun", chinese: "困", binary: "010110", upperTrigram: "lake", lowerTrigram: "water",
    displayName: { pt: "A Exaustão", en: "Oppression (Exhaustion)", es: "La Agotamiento", hi: "उत्पीड़न (थकावट)" },
    judgment: { pt: "Sucesso através da perseverança firme.", en: "Success through firm perseverance.", es: "Éxito a través de la perseverancia firme.", hi: "दृढ़ दृढ़ता के माध्यम से सफलता।" },
    image: { pt: "O lago está seco: Exaustão.", en: "The lake is dry: Exhaustion.", es: "El lago está seco: Agotamiento.", hi: "झील सूखी है: थकावट।" },
    advice: { pt: "Mantenha a fé nas dificuldades.", en: "Keep faith in difficulties.", es: "Mantén la fe en las dificultades.", hi: "मुश्किलों में विश्वास बनाए रखें।" },
    love: { pt: "Prova de fogo no amor. Resista.", en: "Trial by fire in love. Resist.", es: "Prueba de fuego en el amor. Resiste.", hi: "प्रेम में अग्निपरीक्षा। विरोध करें।" },
    career: { pt: "Limitações temporárias. Aguarde.", en: "Temporary limitations. Wait.", es: "Limitaciones temporales. Espera.", hi: "अस्थायी सीमाएं। इंतज़ार करें।" },
    health: { pt: "Falta de energia. Hidratação vital.", en: "Lack of energy. Vital hydration.", es: "Falta de energía. Hidratación vital.", hi: "ऊर्जा की कमी। महत्वपूर्ण जलयोजन।" },
    finance: { pt: "Escassez de recursos. Economize.", en: "Resource scarcity. Save.", es: "Escasez de recursos. Ahorra.", hi: "संसाधनों की कमी। बचत करें।" },
  },
  {
    number: 48, name: "jing", chinese: "井", binary: "011010", upperTrigram: "water", lowerTrigram: "wind",
    displayName: { pt: "O Poço", en: "The Well", es: "El Pozo", hi: "कुआँ" },
    judgment: { pt: "A cidade muda, o poço não.", en: "The city changes, the well does not.", es: "La ciudad cambia, el pozo no.", hi: "शहर बदलता है, कुआँ नहीं।" },
    image: { pt: "Água sobre a madeira: O poço.", en: "Water over wood: The well.", es: "Agua sobre la madera: El pozo.", hi: "लकड़ी पर जल: कुआँ।" },
    advice: { pt: "Busque sua fonte de nutrição interna.", en: "Seek your internal source of nourishment.", es: "Busca tu fuente de nutrición interna.", hi: "अपने आंतरिक पोषण के स्रोत की तलाश करें।" },
    love: { pt: "Amor profundo que sustenta.", en: "Deep love that sustains.", es: "Amor profundo que sustenta.", hi: "गहरा प्रेम जो सहारा देता है।" },
    career: { pt: "Recursos indispensáveis no trabalho.", en: "Indispensable resources at work.", es: "Recursos indispensables en el trabajo.", hi: "काम पर अपरिहार्य संसाधन।" },
    health: { pt: "Pureza interna e hidratação.", en: "Internal purity and hydration.", es: "Pureza interna e hidratación.", hi: "आंतरिक पवित्रता और जलयोजन।" },
    finance: { pt: "Renda estável e confiável.", en: "Stable and reliable income.", es: "Ingresos estables y confiables.", hi: "स्थिर और विश्वसनीय आय।" },
  },
  {
    number: 49, name: "ge", chinese: "革", binary: "101110", upperTrigram: "lake", lowerTrigram: "fire",
    displayName: { pt: "A Revolução", en: "Revolution (Molting)", es: "La Revolución", hi: "क्रांति" },
    judgment: { pt: "No dia marcado, serás acreditado.", en: "On the marked day, you will be believed.", es: "En el día marcado, se te creerá.", hi: "नियत दिन पर, तुम पर विश्वास किया जाएगा।" },
    image: { pt: "Fogo no lago: Revolução.", en: "Fire in the lake: Revolution.", es: "Fuego en el lago: Revolución.", hi: "झील में आग: क्रांति।" },
    advice: { pt: "Mude de pele e renove-se agora.", en: "Molt and renew yourself now.", es: "Cambia de piel y renuévate ahora.", hi: "केंचुल बदलें और अब खुद को नया बनाएं।" },
    love: { pt: "Mudanças profundas no coração.", en: "Deep changes in the heart.", es: "Cambios profundos en el corazón.", hi: "दिल में गहरे बदलाव।" },
    career: { pt: "Reestruturação total e necessária.", en: "Total and necessary restructuring.", es: "Reestructuración total y necesaria.", hi: "पूर्ण और आवश्यक पुनर्गठन।" },
    health: { pt: "Renovação celular e da pele.", en: "Cellular and skin renewal.", es: "Renovación celular y de la piel.", hi: "कोशिकीय और त्वचा का नवीनीकरण।" },
    finance: { pt: "Abandone modelos financeiros velhos.", en: "Abandon old financial models.", es: "Abandona viejos modelos financieros.", hi: "पुराने वित्तीय मॉडलों को छोड़ दें।" },
  },
  {
    number: 50, name: "ding", chinese: "鼎", binary: "101111", upperTrigram: "fire", lowerTrigram: "wind",
    displayName: { pt: "O Caldeirão", en: "The Caldron", es: "El Caldero", hi: "कड़ाही (The Caldron)" },
    judgment: { pt: "Sucesso supremo e fortuna do céu.", en: "Supreme success and heavenly fortune.", es: "Éxito supremo y fortuna del cielo.", hi: "परम सफलता और स्वर्गीय भाग्य।" },
    image: { pt: "Fogo sobre a madeira: O caldeirão.", en: "Fire over wood: The caldron.", es: "Fuego sobre la madera: El caldero.", hi: "लकड़ी पर आग: कड़ाही।" },
    advice: { pt: "Transforme o bruto em sagrado.", en: "Transform the raw into sacred.", es: "Transforma lo bruto en sagrado.", hi: "कच्चे को पवित्र में बदलें।" },
    love: { pt: "Alquimia emocional e união rica.", en: "Emotional alchemy and rich union.", es: "Alquimia emocional y unión rica.", hi: "भावनात्मक कीमिया और समृद्ध मिलन।" },
    career: { pt: "Crie valor e sofisticação.", en: "Create value and sophistication.", es: "Crea valor y sofisticación.", hi: "मूल्य और परिष्कार पैदा करें।" },
    health: { pt: "Nutrição rica e purificante.", en: "Rich and purifying nourishment.", es: "Nutrición rica y purificante.", hi: "समृद्ध और शुद्ध करने वाला पोषण।" },
    finance: { pt: "Prosperidade refinada e sólida.", en: "Refined and solid prosperity.", es: "Prosperidad refinada y sólida.", hi: "परिष्कृत और ठोस समृद्धि।" },
  },
  {
    number: 51, name: "zhen", chinese: "震", binary: "000100", upperTrigram: "thunder", lowerTrigram: "thunder",
    displayName: { pt: "O Trovão", en: "The Arousing (Shock)", es: "El Trueno", hi: "गड़गड़ाहट (झटका)" },
    judgment: { pt: "Choque traz medo, depois riso alegre.", en: "Shock brings fear, then joyful laughter.", es: "El choque trae miedo, luego risas alegres.", hi: "झटका डर लाता है, फिर हर्षित हंसी।" },
    image: { pt: "Trovão duplicado: O despertar.", en: "Double thunder: The arousing.", es: "Trueno duplicado: El despertar.", hi: "दोहरी गड़गड़ाहट: जागृति।" },
    advice: { pt: "Desperte com o choque da realidade.", en: "Wake up with the shock of reality.", es: "Despierta con el choque de la realidad.", hi: "현실 की बिजली (झटके) से जागें।" },
    love: { pt: "Surpresas impactantes no amor.", en: "Impactful surprises in love.", es: "Sorpresas impactantes en el amor.", hi: "प्रेम में प्रभावशाली आश्चर्य।" },
    career: { pt: "Eventos inesperados aceleram tudo.", en: "Unexpected events accelerate everything.", es: "Eventos inesperados aceleran todo.", hi: "अप्रत्याशित घटनाएं सब कुछ तेज कर देती हैं।" },
    health: { pt: "Sistema nervoso em alerta. Descanse.", en: "Nervous system on alert. Rest.", es: "Sistema nervioso en alerta. Descansa.", hi: "तंत्रिका तंत्र सतर्क। आराम करें।" },
    finance: { pt: "Mudanças bruscas de mercado.", en: "Sudden market changes.", es: "Cambios bruscos de mercado.", hi: "बाजार में अचानक बदलाव।" },
  },
  {
    number: 52, name: "ken", chinese: "艮", binary: "100010", upperTrigram: "mountain", lowerTrigram: "mountain",
    displayName: { pt: "A Montanha", en: "Keeping Still (Mountain)", es: "La Montaña", hi: "शांत रहना (पहाड़)" },
    judgment: { pt: "Aquietar o dorso. Não sente o corpo.", en: "Stilling the back. He does not feel his body.", es: "Aquietar el dorso. No siente su cuerpo.", hi: "पीठ को शांत करना। वह अपना शरीर महसूस नहीं करता।" },
    image: { pt: "Montanha sobre montanha: Imobilidade.", en: "Mountain over mountain: Stillness.", es: "Montaña sobre montaña: Inmovilidad.", hi: "पहाड़ पर पहाड़: स्थिरता।" },
    advice: { pt: "Pare, medite e encontre sua paz.", en: "Stop, meditate and find your peace.", es: "Para, medita y encuentra tu paz.", hi: "रुकें, ध्यान करें और अपनी शांति खोजें।" },
    love: { pt: "Pausa necessária e silêncio.", en: "Necessary pause and silence.", es: "Pausa necesaria y silencio.", hi: "आवश्यक विराम और मौन।" },
    career: { pt: "Estabilidade absoluta. Não mude.", en: "Absolute stability. Do not change.", es: "Estabilidad absoluta. No cambies.", hi: "पूर्ण स्थिरता। मत बदलो।" },
    health: { pt: "Postura e saúde da coluna.", en: "Posture and spinal health.", es: "Postura y salud de la columna.", hi: "मुद्रा और रीढ़ की हड्डी का स्वास्थ्य।" },
    finance: { pt: "Mantenha seus ativos imóveis.", en: "Keep your assets still.", es: "Mantén tus activos inmóviles.", hi: "अपनी संपत्ति को स्थिर रखें।" },
  },
  {
    number: 53, name: "jian", chinese: "漸", binary: "001011", upperTrigram: "wind", lowerTrigram: "mountain",
    displayName: { pt: "O Progresso Gradual", en: "Development (Gradual Progress)", es: "El Progreso Gradual", hi: "विकास (धीरे-धीरे प्रगति)" },
    judgment: { pt: "A mulher se casa. Fortuna.", en: "The woman marries. Fortune.", es: "La mujer se casa. Fortuna.", hi: "स्त्री विवाह करती है। भाग्य।" },
    image: { pt: "A árvore na montanha cresce.", en: "The tree on the mountain grows.", es: "El árbol en la montaña crece.", hi: "पहाड़ पर पेड़ उगता है।" },
    advice: { pt: "Avance com paciência e ritmo natural.", en: "Advance with patience and natural rhythm.", es: "Avanza con paciencia y ritmo natural.", hi: "धैर्य और प्राकृतिक लय के साथ आगे बढ़ें।" },
    love: { pt: "Amor que se constrói dia a dia.", en: "Love built day by day.", es: "Amor que se construye día a día.", hi: "दिन-ब-दिन बनने वाला प्यार।" },
    career: { pt: "Sucesso sólido e de longo prazo.", en: "Solid and long-term success.", es: "Éxito sólido y de largo plazo.", hi: "ठोस और दीर्घकालिक सफलता।" },
    health: { pt: "Recuperação lenta e constante.", en: "Slow and constant recovery.", es: "Recuperación lenta y constante.", hi: "धीमी और निरंतर रिकवरी।" },
    finance: { pt: "Crescimento orgânico das economias.", en: "Organic growth of savings.", es: "Crecimiento orgánico de los ahorros.", hi: "बचत की जैविक वृद्धि।" },
  },
  {
    number: 54, name: "gui mei", chinese: "歸妹", binary: "011011", upperTrigram: "thunder", lowerTrigram: "lake",
    displayName: { pt: "A Jovem que se Casa", en: "The Marrying Maiden", es: "La Joven que se Casa", hi: "विवाह करने वाली कन्या" },
    judgment: { pt: "Iniciativas trazem infortúnio.", en: "Undertakings bring misfortune.", es: "Las iniciativas traen infortunio.", hi: "उपक्रम दुर्भाग्य लाते हैं।" },
    image: { pt: "Trovão sobre o lago: Jovem casando.", en: "Thunder over lake: Marrying maiden.", es: "Trueno sobre el lago: Joven casándose.", hi: "झील पर गड़गड़ाहट: विवाह करने वाली कन्या।" },
    advice: { pt: "Cuidado com posições subordinadas.", en: "Watch out for subordinate positions.", es: "Cuidado con posiciones subordinadas.", hi: "अधीनस्थ पदों के साथ सावधान रहें।" },
    love: { pt: "Amor com complicações sociais.", en: "Love with social complications.", es: "Amor con complicaciones sociales.", hi: "सामाजिक जटिलताओं के साथ प्रेम।" },
    career: { pt: "Não force seu lugar na hierarquia.", en: "Don't force your place in hierarchy.", es: "No fuerces tu lugar en la jerarquía.", hi: "पदानुक्रम में अपने स्थान के लिए दबाव न डालें।" },
    health: { pt: "Desejos que exaurem o corpo.", en: "Desires that exhaust the body.", es: "Deseos que agotan el cuerpo.", hi: "ऐसी इच्छाएं जो शरीर को थका देती हैं।" },
    finance: { pt: "Ganhos secundários ou incertos.", en: "Secondary or uncertain gains.", es: "Ganancias secundarias o inciertas.", hi: "द्वितीयक या अनिश्चित लाभ।" },
  },
  {
    number: 55, name: "feng", chinese: "豐", binary: "101100", upperTrigram: "thunder", lowerTrigram: "fire",
    displayName: { pt: "A Abundância", en: "Abundance", es: "La Abundancia", hi: "प्रचुरता" },
    judgment: { pt: "O rei alcança a abundância. Não temas.", en: "The king attains abundance. Be not sad.", es: "El rey alcanza la abundancia. No temas.", hi: "राजा प्रचुरता प्राप्त करता है। उदास न हों।" },
    image: { pt: "Trovão e relâmpago: Abundância.", en: "Thunder and lightning: Abundance.", es: "Trueno y relámpago: Abundancia.", hi: "गड़गड़ाहट और बिजली: प्रचुरता।" },
    advice: { pt: "Aproveite a plenitude e brilhe.", en: "Enjoy the fullness and shine.", es: "Aprovecha la plenitud y brilla.", hi: "पूर्णता का आनंद लें और चमकें।" },
    love: { pt: "Amor pleno e radiante.", en: "Full and radiant love.", es: "Amor pleno y radiante.", hi: "पूर्ण और दीप्तिमान प्रेम।" },
    career: { pt: "Zênite profissional e sucesso total.", en: "Professional zenith and total success.", es: "Cénit profesional y éxito total.", hi: "पेशेवर शिखर और कुल सफलता।" },
    health: { pt: "Grande vitalidade. Cuidado visual.", en: "High vitality. Visual care.", es: "Mucha vitalidad. Cuidado visual.", hi: "उच्च जीवन शक्ति। दृष्टि की देखभाल।" },
    finance: { pt: "Riqueza máxima disponível agora.", en: "Maximum wealth available now.", es: "Riqueza máxima disponible ahora.", hi: "अब अधिकतम धन उपलब्ध है।" },
  },
  {
    number: 56, name: "lü", chinese: "旅", binary: "001101", upperTrigram: "fire", lowerTrigram: "mountain",
    displayName: { pt: "O Viajante", en: "The Wanderer", es: "El Viajero", hi: "यात्री" },
    judgment: { pt: "Sucesso em pequenas coisas através da retidão.", en: "Success in small things through rectitude.", es: "Éxito en pequeñas cosas a través de la rectitud.", hi: "सत्यनिष्ठा के माध्यम से छोटी बातों में सफलता।" },
    image: { pt: "Fogo sobre a montanha: O viajante.", en: "Fire on the mountain: The wanderer.", es: "Fuego sobre la montaña: El viajero.", hi: "पहार पर आग: यात्री।" },
    advice: { pt: "Aja com humildade e cautela em terras estranhas.", en: "Act with humility and caution in strange lands.", es: "Actúa con humildad y cautela en tierras extrañas.", hi: "अजनबी भूमियों में विनम्रता और सावधानी के साथ कार्य करें।" },
    love: { pt: "Conexões passageiras ou em viagens.", en: "Fleeting connections or while traveling.", es: "Conexiones pasajeras o en viajes.", hi: "क्षणिक संबंध या यात्रा के दौरान।" },
    career: { pt: "Adapte-se a novos ambientes de trabalho.", en: "Adapt to new work environments.", es: "Adáptate a nuevos entornos de trabajo.", hi: "काम के नए वातावरण के अनुकूल बनें।" },
    health: { pt: "Resistência física durante deslocamentos.", en: "Physical stamina during travel.", es: "Resistencia física durante desplazamientos.", hi: "यात्रा के दौरान शारीरिक सहनशक्ति।" },
    finance: { pt: "Foque na segurança imediata dos recursos.", en: "Focus on immediate security of resources.", es: "Enfócate en la seguridad inmediata de recursos.", hi: "संसाधनों की तत्काल सुरक्षा पर ध्यान दें।" },
  },
  {
    number: 57, name: "sun", chinese: "巽", binary: "011011", upperTrigram: "wind", lowerTrigram: "wind",
    displayName: { pt: "O Suave (O Vento)", en: "The Gentle (Wind)", es: "Lo Suave (Viento)", hi: "कोमल (हवा)" },
    judgment: { pt: "Sucesso em pequenas coisas. Favorece a ação.", en: "Success in small things. Favors action.", es: "Éxito en pequeñas cosas. Favorece la acción.", hi: "छोटी बातों में सफलता। कार्रवाई का पक्ष लेती है।" },
    image: { pt: "Vento duplicado: O suave.", en: "Double wind: The gentle.", es: "Viento duplicado: Lo suave.", hi: "दोहरी हवा: कोमल।" },
    advice: { pt: "Persista suavemente para influenciar.", en: "Persist gently to influence.", es: "Persiste suavemente para influenciar.", hi: "प्रभावित करने के लिए धीरे से डटे रहें।" },
    love: { pt: "Comunicação sutil e persuasiva.", en: "Subtle and persuasive communication.", es: "Comunicación sutil y persuasiva.", hi: "सूक्ष्म और प्रेरक संचार।" },
    career: { pt: "Influencie através da constância e tato.", en: "Influence through constancy and tact.", es: "Influencia a través de la constancia y el tacto.", hi: "निरंतरता और शिष्टता के माध्यम से प्रभावित करें।" },
    health: { pt: "Saúde do sistema respiratório.", en: "Respiratory system health.", es: "Salud del sistema respiratorio.", hi: "श्वसन तंत्र का स्वास्थ्य।" },
    finance: { pt: "Ganhos graduais e bem planejados.", en: "Gradual and well-planned gains.", es: "Ganancias graduales y bien planeadas.", hi: "धीरे-धीरे और अच्छी तरह से नियोजित लाभ।" },
  },
  {
    number: 58, name: "dui", chinese: "兌", binary: "110110", upperTrigram: "lake", lowerTrigram: "lake",
    displayName: { pt: "O Sereno (O Lago)", en: "The Joyous (Lake)", es: "Lo Sereno (Lago)", hi: "हर्षित (झील)" },
    judgment: { pt: "Sucesso. Perseverança traz fortuna.", en: "Success. Perseverance brings fortune.", es: "Éxito. La perseverancia trae fortuna.", hi: "सफलता। दृढ़ता भाग्य लाती है।" },
    image: { pt: "Lagos unidos: A serenidade e alegria.", en: "United lakes: Serenity and joy.", es: "Lagos unidos: La serenidad y alegría.", hi: "संयुक्त झीलें: शांति और खुशी।" },
    advice: { pt: "Comunique-se com alegria e verdade.", en: "Communicate with joy and truth.", es: "Comunícate con alegría y verdad.", hi: "खुशी और सच्चाई के साथ संवाद करें।" },
    love: { pt: "Pura alegria e prazer compartilhado.", en: "Pure joy and shared pleasure.", es: "Pura alegría y placer compartido.", hi: "शुद्ध खुशी और साझा आनंद।" },
    career: { pt: "Harmonia e boa comunicação no trabalho.", en: "Harmony and good communication at work.", es: "Armonía y buena comunicación en el trabajo.", hi: "काम पर सद्भाव और अच्छा संचार।" },
    health: { pt: "Equilíbrio emocional e vitalidade.", en: "Emotional balance and vitality.", es: "Equilibrio emocional y vitalidad.", hi: "भावनात्मक संतुलन और जीवन शक्ति।।" },
    finance: { pt: "Ganhos em atividades sociais.", en: "Gains in social activities.", es: "Ganancias en actividades sociales.", hi: "सामाजिक गतिविधियों में लाभ।" },
  },
  {
    number: 59, name: "huan", chinese: "渙", binary: "010011", upperTrigram: "wind", lowerTrigram: "water",
    displayName: { pt: "A Dissolução", en: "Dispersion (Dissolution)", es: "La Disolución", hi: "परिक्षेपण (विघटन)" },
    judgment: { pt: "Sucesso. O rei se aproxima do templo.", en: "Success. The king approaches the temple.", es: "Éxito. El rey se acerca al templo.", hi: "सफलता। राजा मंदिर की ओर बढ़ता है।" },
    image: { pt: "Vento sobre a água: A dispersão.", en: "Wind over water: Dispersion.", es: "Viento sobre el agua: La dispersión.", hi: "पनी पर हवा: परिक्षेपण।" },
    advice: { pt: "Dissolva o egoísmo e busque a união.", en: "Dissolve selfishness and seek union.", es: "Disuelve el egoísmo y busca la unión.", hi: "स्वार्थ को त्यागें और एकता की तलाश करें।" },
    love: { pt: "Superação de barreiras emocionais.", en: "Overcoming emotional barriers.", es: "Superación de barreras emocionales.", hi: "भावनात्मक बाधाओं पर काबू पाना।" },
    career: { pt: "Dissolva bloqueios em projetos.", en: "Dissolve blocks in projects.", es: "Disuelve bloqueos en proyectos.", hi: "प्रोजेक्ट्स में बाधाओं को दूर करें।" },
    health: { pt: "Limpeza de fluídos e desintoxicação.", en: "Fluid cleansing and detox.", es: "Limpieza de fluidos y desintoxicación.", hi: "तरल सफाई और विषहरण।" },
    finance: { pt: "Recursos fluem livremente agora.", en: "Resources flow freely now.", es: "Los recursos fluyen libremente ahora.", hi: "संसाधन अब स्वतंत्र रूप से बहते हैं।" },
  },
  {
    number: 60, name: "jie", chinese: "節", binary: "110010", upperTrigram: "water", lowerTrigram: "lake",
    displayName: { pt: "A Delimitação", en: "Limitation", es: "La Delimitación", hi: "सीमा" },
    judgment: { pt: "Limitação traz sucesso. Não deve ser amarga.", en: "Limitation brings success. Should not be bitter.", es: "La delimitación trae éxito. No debe ser amarga.", hi: "सीमा सफलता लाती है। यह कड़वी नहीं होनी चाहिए।" },
    image: { pt: "Água sobre o lago: Delimitação.", en: "Water over the lake: Limitation.", es: "Agua sobre el lago: Delimitación.", hi: "झील पर जल: सीमा।" },
    advice: { pt: "Aceite limites necessários com economia.", en: "Accept necessary limits with economy.", es: "Acepta límites necesarios con economía.", hi: "किफायत के साथ आवश्यक सीमाओं को स्वीकार करें।" },
    love: { pt: "Privacidade e limites saudáveis.", en: "Privacy and healthy limits.", es: "Privacidad y límites saludables.", hi: "गोपनीयता और स्वस्थ सीमाएं।" },
    career: { pt: "Ajuste-se ao escopo do trabalho.", en: "Adjust to the work scope.", es: "Ajústate al alcance del trabajo.", hi: "कार्य के दायरे में तालमेल बिठाएं।" },
    health: { pt: "Moderação em todas as atividades.", en: "Moderation in all activities.", es: "Moderación en todas las actividades.", hi: "सभी गतिविधियों में संयम।" },
    finance: { pt: "Orçamento rigoroso traz fortuna.", en: "Rigorous budget brings fortune.", es: "Un presupuesto riguroso trae fortuna.", hi: "कठोर बजट भाग्य लाता है।" },
  },
  {
    number: 61, name: "zhong fu", chinese: "中孚", binary: "110011", upperTrigram: "wind", lowerTrigram: "lake",
    displayName: { pt: "Verdade Interior", en: "Inner Truth", es: "Verdad Interior", hi: "आंतरिक सत्य" },
    judgment: { pt: "Sucesso supremo se houver sinceridade.", en: "Supreme success if there is sincerity.", es: "Éxito supremo si hay sinceridad.", hi: "यदि सच्चाई हो तो परम सफलता।" },
    image: { pt: "O vento acima do lago: Verdade.", en: "Wind above the lake: Truth.", es: "Viento sobre el lago: Verdad.", hi: "झील के ऊपर हवा: सच्चाई।" },
    advice: { pt: "Ouça seu coração com sabedoria.", en: "Listen to your heart with wisdom.", es: "Escucha a tu corazón con sabiduría.", hi: "बुद्धिमानी के साथ अपने दिल की सुनें।" },
    love: { pt: "Sinceridade e lealdade profunda.", en: "Sincerity and deep loyalty.", es: "Sinceridad y lealtad profunda.", hi: "सच्चाई और गहरी वफादारी।" },
    career: { pt: "Sucesso através da integridade absoluta.", en: "Success through absolute integrity.", es: "Éxito a través de la integridad absoluta.", hi: "पूर्ण सत्यनिष्ठा के माध्यम से सफलता।" },
    health: { pt: "Equilíbrio emocional profundo.", en: "Deep emotional balance.", es: "Equilibrio emocional profundo.", hi: "गहरा भावनात्मक संतुलन।" },
    finance: { pt: "Transações transparentes e honestas.", en: "Transparent and honest transactions.", es: "Transacciones transparentes y honestas.", hi: "पारदर्शी और ईमानदार लेनदेन।" },
  },
  {
    number: 62, name: "xiao guo", chinese: "小過", binary: "001100", upperTrigram: "thunder", lowerTrigram: "mountain",
    displayName: { pt: "Pequeno Excesso", en: "Preponderance of the Small", es: "Pequeño Exceso", hi: "छोटों की प्रचुरता" },
    judgment: { pt: "Sucesso em pequenas coisas através da humildade.", en: "Success in small things through humility.", es: "Éxito en pequeñas cosas a través de la humildad.", hi: "विनम्रता के माध्यम से छोटी बातों में सफलता।" },
    image: { pt: "Trovão sobre a montanha: Pequeno excesso.", en: "Thunder over the mountain: Small excess.", es: "Trueno sobre la montaña: Pequeño exceso.", hi: "पहाड़ पर गड़गड़ाहट: छोटों की प्रचुरता।" },
    advice: { pt: "Foque nos detalhes e na simplicidade.", en: "Focus on details and simplicity.", es: "Enfócate en los detalles y la sencillez.", hi: "विवरण और सादगी पर ध्यान दें।" },
    love: { pt: "Pequenos gestos de carinho importam.", en: "Small gestures of affection matter.", es: "Los pequeños gestos de cariño importan.", hi: "स्नेह के छोटे इशारे मायने रखते हैं।" },
    career: { pt: "Excelente para tarefas operacionais.", en: "Excellent for operational tasks.", es: "Excelente para tareas operativas.", hi: "परिचालन कार्यों के लिए उत्कृष्ट।" },
    health: { pt: "Cuide de pequenos desconfortos.", en: "Care for small discomforts.", es: "Cuida los pequeños malestares.", hi: "छोटी-छोटी परेशानियों का ख्याल रखें।" },
    finance: { pt: "Economia em pequenos gastos.", en: "Saving on small expenses.", es: "Ahorro en gastos pequeños.", hi: "छोटे खर्चों में बचत।" },
  },
  {
    number: 63, name: "ji ji", chinese: "既濟", binary: "101010", upperTrigram: "water", lowerTrigram: "fire",
    displayName: { pt: "Após a Conclusão", en: "After Completion", es: "Después de la Conclusión", hi: "पूरा होने के बाद" },
    judgment: { pt: "Sucesso em pequenas coisas. Manter fortuna.", en: "Success in small things. Maintain fortune.", es: "Éxito en pequeñas cosas. Mantener fortuna.", hi: "छोटी बातों में सफलता। भाग्य बनाए रखें।" },
    image: { pt: "Água acima do fogo: Após conclusão.", en: "Water above fire: After completion.", es: "Agua sobre el fuego: Tras concluir.", hi: "आग के ऊपर जल: पूरा होने के बाद।" },
    advice: { pt: "Mantenha a guarda após atingir o objetivo.", en: "Keep your guard after reaching the goal.", es: "Mantén la guardia tras alcanzar la meta.", hi: "लक्ष्य तक पहुँचने के बाद अपनी सुरक्षा बनाए रखें।" },
    love: { pt: "Plenitude e harmonia estabilizada.", en: "Fullness and stabilized harmony.", es: "Plenitud y armonía estabilizada.", hi: "पूर्णता और स्थिर सद्भाव।" },
    career: { pt: "Projeto concluído. Próximo passo planejado.", en: "Project completed. Next step planned.", es: "Proyecto concluido. Próximo paso planeado.", hi: "प्रोजेक्ट पूरा हुआ। अगला कदम नियोजित।" },
    health: { pt: "Saúde estável, não relaxe nos cuidados.", en: "Stable health, don't relax care.", es: "Salud estable, no descuides los cuidados.", hi: "स्थिर स्वास्थ्य, देखभाल में ढील न दें।" },
    finance: { pt: "Situação financeira consolidada.", en: "Consolidated financial status.", es: "Situación financiera consolidada.", hi: "समेकित वित्तीय स्थिति।" },
  },
  {
    number: 64, name: "wei ji", chinese: "未濟", binary: "010101", upperTrigram: "fire", lowerTrigram: "water",
    displayName: { pt: "Antes da Conclusão", en: "Before Completion", es: "Antes de la Conclusión", hi: "पूरा होने से पहले" },
    judgment: { pt: "Sucesso. A raposinha quase atravessa.", en: "Success. Little fox almost gets across.", es: "Éxito. El zorrito casi cruza.", hi: "सफलता। नन्हा लोमड़ी लगभग पार हो जाता है।" },
    image: { pt: "Fogo acima da água: Antes da conclusão.", en: "Fire above the water: Before completion.", es: "Fuego arriba del agua: Antes de concluir.", hi: "पानी के ऊपर आग: पूरा होने से पहले।" },
    advice: { pt: "Prepare-se para o novo ciclo que inicia.", en: "Prepare for the new cycle beginning.", es: "Prepárate para el nuevo ciclo que inicia.", hi: "शुरू होने वाले नए चक्र के लिए तैयारी करें।" },
    love: { pt: "Novas esperanças e começos próximos.", en: "New hopes and upcoming beginnings.", es: "Nuevas esperanzas y comienzos próximos.", hi: "नई आशाएं और आगामी शुरुआत।" },
    career: { pt: "Um novo capítulo se aproxima.", en: "A new chapter is approaching.", es: "Un nuevo capítulo se aproxima.", hi: "एक नया अध्याय नज़दीक है।" },
    health: { pt: "Renovação profunda de energias.", en: "Deep renewal of energies.", es: "Renovación profunda de energías.", hi: "ऊर्जा का गहरा नवीनीकरण।" },
    finance: { pt: "Novas fontes de renda saindo do papel.", en: "New income sources taking shape.", es: "Nuevas fuentes de ingreso gestándose.", hi: "आय के नए स्रोत आकार ले रहे हैं।" },
  }
];

export function getHexagramByNumber(number: number): IChingHexagram | undefined {
  return I_CHING_HEXAGRAMS.find(h => h.number === number);
}

export function getHexagramByName(name: string, lang: string = "en"): IChingHexagram | undefined {
  return I_CHING_HEXAGRAMS.find(
    h => h.name.toLowerCase() === name.toLowerCase() ||
         (h.displayName as any)[lang]?.toLowerCase().includes(name.toLowerCase()) ||
         h.displayName.pt.toLowerCase().includes(name.toLowerCase())
  );
}

export function getDailyHexagram(date: Date = new Date()): IChingHexagram {
  const dayOfYear = Math.floor((date.getTime() - new Date(date.getFullYear(), 0, 0).getTime()) / 86400000);
  return I_CHING_HEXAGRAMS[dayOfYear % I_CHING_HEXAGRAMS.length] || I_CHING_HEXAGRAMS[0]!;
}

export function getHexagramForQuestion(question: string): IChingHexagram {
  const hash = question.split("").reduce((acc, char) => acc + char.charCodeAt(0), 0);
  return I_CHING_HEXAGRAMS[hash % I_CHING_HEXAGRAMS.length] || I_CHING_HEXAGRAMS[0]!;
}
